import { DieModel } from '../types/die';
import { RobotModelSpec, ToolCenterPoint, SprayHeadType, SprayNozzleConfig, HotSpotDefinition, EoatType, EOATSpec } from '../types/robot';
import { DieCastingMachine } from '../types/machine';
import { Waypoint } from '../types/path';

export const TOYO_DCM_FAMILY: DieCastingMachine[] = [
  {
    id: 'toyo-bd-125v7ex',
    name: 'Toyo BD-125V7EX (1,250 kN / 125T)',
    modelCode: 'BD-125V7EX',
    manufacturer: 'TOYO',
    clampingForceKn: 1250,
    clampingForceTons: 125,
    tieBarClearanceH: 460,
    tieBarClearanceV: 460,
    tieBarDiameter: 85,
    platenWidth: 700,
    platenHeight: 700,
    movablePlatenWidth: 700,
    movablePlatenHeight: 700,
    maxDieOpeningStroke: 350,
    minDieHeight: 250,
    maxDieHeight: 500,
    ejectorStroke: 75,
    injectionAxisOffsetY: -100,
    safetyEnclosureDepth: 2200,
    plungerLubricatorModel: 'DM05/DC-TY-B1',
    plungerStroke: 305,
    standardPlungerDia: 50,
    machineLengthMm: 4585,
    machineWidthMm: 1575,
    machineHeightMm: 2207,
    machineWeightTons: 5.5,
    dryCycleTimeSec: 6.0,
    controlSystem: 'SYSTEM 700EX',
    pumpMotorPower: '15kW 6P AC200V',
    oilTankCapacityL: 330
  },
  {
    id: 'toyo-bd-200v7ex',
    name: 'Toyo BD-200V7EX (2,000 kN / 200T)',
    modelCode: 'BD-200V7EX',
    manufacturer: 'TOYO',
    clampingForceKn: 2000,
    clampingForceTons: 200,
    tieBarClearanceH: 508,
    tieBarClearanceV: 530,
    tieBarDiameter: 100,
    platenWidth: 820,
    platenHeight: 820,
    movablePlatenWidth: 820,
    movablePlatenHeight: 820,
    maxDieOpeningStroke: 350,
    minDieHeight: 250,
    maxDieHeight: 600,
    ejectorStroke: 80,
    injectionAxisOffsetY: -125,
    safetyEnclosureDepth: 2400,
    plungerLubricatorModel: 'DM05/DC-TY-B1',
    plungerStroke: 370,
    standardPlungerDia: 50,
    machineLengthMm: 5407,
    machineWidthMm: 1796,
    machineHeightMm: 2545,
    machineWeightTons: 8.0,
    dryCycleTimeSec: 7.7,
    controlSystem: 'SYSTEM 700EX',
    pumpMotorPower: '15kW 6P AC200V',
    oilTankCapacityL: 400
  },
  {
    id: 'toyo-bd-250v7ex',
    name: 'Toyo BD-250V7EX (2,500 kN / 250T)',
    modelCode: 'BD-250V7EX',
    manufacturer: 'TOYO',
    clampingForceKn: 2500,
    clampingForceTons: 250,
    tieBarClearanceH: 584,
    tieBarClearanceV: 584,
    tieBarDiameter: 110,
    platenWidth: 850,
    platenHeight: 850,
    movablePlatenWidth: 850,
    movablePlatenHeight: 904,
    maxDieOpeningStroke: 380,
    minDieHeight: 250,
    maxDieHeight: 600,
    ejectorStroke: 80,
    injectionAxisOffsetY: -125,
    safetyEnclosureDepth: 2600,
    plungerLubricatorModel: 'DM05/DC-TY-B1',
    plungerStroke: 370,
    standardPlungerDia: 60,
    machineLengthMm: 5603,
    machineWidthMm: 1947,
    machineHeightMm: 2601,
    machineWeightTons: 9.0,
    dryCycleTimeSec: 7.0,
    controlSystem: 'SYSTEM 700EX',
    pumpMotorPower: '22kW 6P AC200V',
    oilTankCapacityL: 410
  },
  {
    id: 'toyo-bd-350v7ex',
    name: 'Toyo BD-350V7EX (3,500 kN / 350T)',
    modelCode: 'BD-350V7EX',
    manufacturer: 'TOYO',
    clampingForceKn: 3500,
    clampingForceTons: 350,
    tieBarClearanceH: 652,
    tieBarClearanceV: 652,
    tieBarDiameter: 125,
    platenWidth: 935,
    platenHeight: 1008,
    movablePlatenWidth: 935,
    movablePlatenHeight: 1008,
    maxDieOpeningStroke: 420,
    minDieHeight: 300,
    maxDieHeight: 700,
    ejectorStroke: 100,
    injectionAxisOffsetY: -150,
    safetyEnclosureDepth: 2800,
    plungerLubricatorModel: 'DM05/DC-TY-B1',
    plungerStroke: 425,
    standardPlungerDia: 70,
    machineLengthMm: 6185,
    machineWidthMm: 2019,
    machineHeightMm: 2786,
    machineWeightTons: 12.0,
    dryCycleTimeSec: 10.9,
    controlSystem: 'SYSTEM 700EX',
    pumpMotorPower: '22kW 6P AC200V',
    oilTankCapacityL: 500
  },
  {
    id: 'toyo-bd-500v7ex',
    name: 'Toyo BD-500V7EX (5,000 kN / 500T)',
    modelCode: 'BD-500V7EX',
    manufacturer: 'TOYO',
    clampingForceKn: 5000,
    clampingForceTons: 500,
    tieBarClearanceH: 751,
    tieBarClearanceV: 751,
    tieBarDiameter: 140,
    platenWidth: 1175.5,
    platenHeight: 1200,
    movablePlatenWidth: 1070,
    movablePlatenHeight: 1172,
    maxDieOpeningStroke: 560,
    minDieHeight: 350,
    maxDieHeight: 850,
    ejectorStroke: 110,
    injectionAxisOffsetY: -175,
    safetyEnclosureDepth: 3200,
    plungerLubricatorModel: 'DM10/DC-TY-B1',
    plungerStroke: 580,
    standardPlungerDia: 80,
    machineLengthMm: 7386,
    machineWidthMm: 2416,
    machineHeightMm: 2945,
    machineWeightTons: 19.0,
    dryCycleTimeSec: 11.1,
    controlSystem: 'SYSTEM 700EX',
    pumpMotorPower: '37kW 6P AC200V',
    oilTankCapacityL: 890
  },
  {
    id: 'toyo-bd-650v7ex',
    name: 'Toyo BD-650V7EX (6,500 kN / 650T)',
    modelCode: 'BD-650V7EX',
    manufacturer: 'TOYO',
    clampingForceKn: 6500,
    clampingForceTons: 650,
    tieBarClearanceH: 850,
    tieBarClearanceV: 850,
    tieBarDiameter: 160,
    platenWidth: 1320,
    platenHeight: 1335,
    movablePlatenWidth: 1200,
    movablePlatenHeight: 1302,
    maxDieOpeningStroke: 660,
    minDieHeight: 350,
    maxDieHeight: 900,
    ejectorStroke: 125,
    injectionAxisOffsetY: -225,
    safetyEnclosureDepth: 3400,
    plungerLubricatorModel: 'DM10/DC-TY-B1',
    plungerStroke: 670,
    standardPlungerDia: 80,
    machineLengthMm: 7830,
    machineWidthMm: 2495,
    machineHeightMm: 2972,
    machineWeightTons: 25.0,
    dryCycleTimeSec: 13.2,
    controlSystem: 'SYSTEM 700EX',
    pumpMotorPower: '37kW 6P AC200V',
    oilTankCapacityL: 920
  },
  {
    id: 'toyo-bd-800v7ex',
    name: 'Toyo BD-800V7EX (8,000 kN / 800T)',
    modelCode: 'BD-800V7EX',
    manufacturer: 'TOYO',
    clampingForceKn: 8000,
    clampingForceTons: 800,
    tieBarClearanceH: 931,
    tieBarClearanceV: 931,
    tieBarDiameter: 180,
    platenWidth: 1440.5,
    platenHeight: 1475,
    movablePlatenWidth: 1400,
    movablePlatenHeight: 1442,
    maxDieOpeningStroke: 760,
    minDieHeight: 400,
    maxDieHeight: 950,
    ejectorStroke: 125,
    injectionAxisOffsetY: -275,
    safetyEnclosureDepth: 3600,
    plungerLubricatorModel: 'DM10/DC-TY-B1',
    plungerStroke: 750,
    standardPlungerDia: 90,
    machineLengthMm: 8622,
    machineWidthMm: 2753,
    machineHeightMm: 3360,
    machineWeightTons: 32.0,
    dryCycleTimeSec: 15.3,
    controlSystem: 'SYSTEM 700EX',
    pumpMotorPower: '45kW 6P AC200V',
    oilTankCapacityL: 970
  },
  {
    id: 'toyo-bd-1000v7ex',
    name: 'Toyo BD-1000V7EX (10,000 kN / 1000T)',
    modelCode: 'BD-1000V7EX',
    manufacturer: 'TOYO',
    clampingForceKn: 10000,
    clampingForceTons: 1000,
    tieBarClearanceH: 931,
    tieBarClearanceV: 931,
    tieBarDiameter: 190,
    platenWidth: 1440.5,
    platenHeight: 1475,
    movablePlatenWidth: 1400,
    movablePlatenHeight: 1442,
    maxDieOpeningStroke: 760,
    minDieHeight: 400,
    maxDieHeight: 950,
    ejectorStroke: 125,
    injectionAxisOffsetY: -275,
    safetyEnclosureDepth: 3600,
    plungerLubricatorModel: 'DM10/DC-TY-B1',
    plungerStroke: 750,
    standardPlungerDia: 100,
    machineLengthMm: 8622,
    machineWidthMm: 2753,
    machineHeightMm: 3360,
    machineWeightTons: 33.0,
    dryCycleTimeSec: 17.9,
    controlSystem: 'SYSTEM 700EX',
    pumpMotorPower: '45kW 6P AC200V',
    oilTankCapacityL: 970
  },
  {
    id: 'toyo-bd-1250v7ex',
    name: 'Toyo BD-1250V7EX (12,500 kN / 1250T)',
    modelCode: 'BD-1250V7EX',
    manufacturer: 'TOYO',
    clampingForceKn: 12500,
    clampingForceTons: 1250,
    tieBarClearanceH: 1150,
    tieBarClearanceV: 1150,
    tieBarDiameter: 230,
    platenWidth: 1800,
    platenHeight: 1800,
    movablePlatenWidth: 1800,
    movablePlatenHeight: 1800,
    maxDieOpeningStroke: 900,
    minDieHeight: 600,
    maxDieHeight: 1500,
    ejectorStroke: 200,
    injectionAxisOffsetY: -350,
    safetyEnclosureDepth: 4500,
    plungerLubricatorModel: 'L-15',
    plungerStroke: 950,
    standardPlungerDia: 120,
    machineLengthMm: 13003,
    machineWidthMm: 3273,
    machineHeightMm: 4538,
    machineWeightTons: 66.0,
    dryCycleTimeSec: 20.8,
    controlSystem: 'SYSTEM 700EX',
    pumpMotorPower: '45kW+30kW 6P AC200V',
    oilTankCapacityL: 1800
  }
];

export const MACHINE_PRESETS: DieCastingMachine[] = TOYO_DCM_FAMILY;

export const ROBOT_PRESETS: RobotModelSpec[] = [
  {
    id: 'yaskawa-gp50',
    name: 'Yaskawa Motoman GP50 (Die-Casting Heavy / Spray Spec)',
    manufacturer: 'YASKAWA',
    payloadKg: 50,
    reachMm: 2061,
    repeatabilityMm: 0.07,
    degreesOfFreedom: 6,
    baseOffset: [0, 1350, -645],
    mountOrientation: 'top',
    jointLimits: [
      { minDeg: -180, maxDeg: 180, maxVelocityDegPerSec: 180 },
      { minDeg: -90, maxDeg: 135, maxVelocityDegPerSec: 180 },
      { minDeg: -175, maxDeg: 250, maxVelocityDegPerSec: 180 },
      { minDeg: -360, maxDeg: 360, maxVelocityDegPerSec: 250 },
      { minDeg: -125, maxDeg: 125, maxVelocityDegPerSec: 250 },
      { minDeg: -360, maxDeg: 360, maxVelocityDegPerSec: 360 }
    ],
    dhParams: []
  },
  {
    id: 'yaskawa-gp25-12',
    name: 'Yaskawa Motoman GP25-12 (Extended Reach Die Spray)',
    manufacturer: 'YASKAWA',
    payloadKg: 25,
    reachMm: 2010,
    repeatabilityMm: 0.05,
    degreesOfFreedom: 6,
    baseOffset: [0, 1350, -645],
    mountOrientation: 'top',
    jointLimits: [
      { minDeg: -180, maxDeg: 180, maxVelocityDegPerSec: 210 },
      { minDeg: -105, maxDeg: 150, maxVelocityDegPerSec: 210 },
      { minDeg: -175, maxDeg: 240, maxVelocityDegPerSec: 265 },
      { minDeg: -360, maxDeg: 360, maxVelocityDegPerSec: 420 },
      { minDeg: -150, maxDeg: 150, maxVelocityDegPerSec: 420 },
      { minDeg: -360, maxDeg: 360, maxVelocityDegPerSec: 800 }
    ],
    dhParams: []
  },
  {
    id: 'fanuc-m710ic-50',
    name: 'FANUC M-710iC/50 (Foundry Spec)',
    manufacturer: 'FANUC',
    payloadKg: 50,
    reachMm: 2050,
    repeatabilityMm: 0.03,
    degreesOfFreedom: 6,
    baseOffset: [0, 1350, -645],
    mountOrientation: 'top',
    jointLimits: [
      { minDeg: -180, maxDeg: 180, maxVelocityDegPerSec: 175 },
      { minDeg: -90, maxDeg: 135, maxVelocityDegPerSec: 175 },
      { minDeg: -170, maxDeg: 260, maxVelocityDegPerSec: 175 },
      { minDeg: -360, maxDeg: 360, maxVelocityDegPerSec: 250 },
      { minDeg: -125, maxDeg: 125, maxVelocityDegPerSec: 250 },
      { minDeg: -360, maxDeg: 360, maxVelocityDegPerSec: 355 }
    ],
    dhParams: []
  },
  {
    id: 'abb-irb-4600',
    name: 'ABB IRB 4600-40/2.55 (Foundry Plus 2)',
    manufacturer: 'ABB',
    payloadKg: 40,
    reachMm: 2550,
    repeatabilityMm: 0.05,
    degreesOfFreedom: 6,
    baseOffset: [-1050, 120, 0],
    mountOrientation: 'side',
    jointLimits: [
      { minDeg: -180, maxDeg: 180, maxVelocityDegPerSec: 175 },
      { minDeg: -90, maxDeg: 150, maxVelocityDegPerSec: 175 },
      { minDeg: -180, maxDeg: 75, maxVelocityDegPerSec: 175 },
      { minDeg: -300, maxDeg: 300, maxVelocityDegPerSec: 250 },
      { minDeg: -120, maxDeg: 120, maxVelocityDegPerSec: 250 },
      { minDeg: -360, maxDeg: 360, maxVelocityDegPerSec: 360 }
    ],
    dhParams: []
  },
  {
    id: 'kuka-kr60-3',
    name: 'KUKA KR 60-3 Foundry',
    manufacturer: 'KUKA',
    payloadKg: 60,
    reachMm: 2033,
    repeatabilityMm: 0.06,
    degreesOfFreedom: 6,
    baseOffset: [-1000, 150, 0],
    mountOrientation: 'side',
    jointLimits: [
      { minDeg: -185, maxDeg: 185, maxVelocityDegPerSec: 156 },
      { minDeg: -135, maxDeg: 35, maxVelocityDegPerSec: 156 },
      { minDeg: -120, maxDeg: 158, maxVelocityDegPerSec: 156 },
      { minDeg: -350, maxDeg: 350, maxVelocityDegPerSec: 330 },
      { minDeg: -119, maxDeg: 119, maxVelocityDegPerSec: 330 },
      { minDeg: -350, maxDeg: 350, maxVelocityDegPerSec: 615 }
    ],
    dhParams: []
  },
  {
    id: 'linear-reciprocator',
    name: 'Wollin / Rimrock 2-Axis Linear Reciprocator',
    manufacturer: 'LINEAR_RECIPROCATOR',
    payloadKg: 45,
    reachMm: 1800,
    repeatabilityMm: 0.2,
    degreesOfFreedom: 2,
    baseOffset: [-900, 0, 300],
    mountOrientation: 'top_machine_mount',
    jointLimits: [
      { minDeg: -1800, maxDeg: 1800, maxVelocityDegPerSec: 500 },
      { minDeg: -1200, maxDeg: 1200, maxVelocityDegPerSec: 500 },
      { minDeg: 0, maxDeg: 0, maxVelocityDegPerSec: 0 },
      { minDeg: 0, maxDeg: 0, maxVelocityDegPerSec: 0 },
      { minDeg: 0, maxDeg: 0, maxVelocityDegPerSec: 0 },
      { minDeg: 0, maxDeg: 0, maxVelocityDegPerSec: 0 }
    ],
    dhParams: []
  }
];

export interface SprayHeadPreset {
  id: SprayHeadType;
  name: string;
  category: string;
  description: string;
  manifoldType: 'single_nozzle' | 'dual_sided_matrix' | 'multi_head_linear' | 'micro_spray' | 'monoblock' | 'modular_frame' | 'matrix_grid' | 'micro_dosing';
  manifoldWidthMm: number;
  nozzleCount: number;
  weightKg: number;
  defaultSprayDistanceMm: number;
  nozzles: SprayNozzleConfig[];
  eoatSpec?: EOATSpec;
  cycleTimeAdvantageSec?: number;
  cycleTimeNote?: string;
  costTier?: 'STANDARD' | 'MID_RANGE' | 'PREMIUM' | 'HIGH_END';
  costTierLabel?: string;
  maintenanceComplexity?: 'LOW' | 'MEDIUM' | 'HIGH';
  maintenanceNotes?: string;
  nozzleAdjustabilityDetails?: string;
  fluidAirSupply?: {
    lubePressure: string;
    airPressure: string;
    lubeFlowRate: string;
    airConsumptionNlPerMin: number;
    connectionInterfaces: string;
    lubricantPressureBar?: number;
    airPressureBar?: number;
    antiDripSuckBack?: boolean;
    airKnifeIntegrated?: boolean;
  };
  microSpraySettings?: {
    fineSpray: boolean;
    sprayWidthMm: number;
    applicationRateMlPerSec: number;
  };
  conventionalSettings?: {
    liquidFlowMlPerSec: number;
    airPressureBar: number;
    sprayWidthMm: number;
  };
}

export const EOAT_PRESETS: EOATSpec[] = [
  {
    id: 'MONOBLOCK',
    type: 'MONOBLOCK',
    name: 'Monoblock High-Volume Manifold',
    subtitle: 'Machined 6061-T6 Billet Block • Integrated Fluid Channels',
    category: 'Dedicated High-Volume Tooling',
    description: 'Compact machined aluminum/stainless manifold with integrated internal gun-drilled fluid channels, fixed precision nozzle positions, and minimal external fittings or hoses. Built for structural rigidity, zero hose-pinch risk, and continuous high-volume production.',
    weightKg: 12.5,
    dimensionsMm: {
      width: 340,
      height: 130,
      depth: 85,
      clearanceRadius: 190
    },
    mountingInterface: 'ISO 9409-1-100-6-M8 (Direct Rigid Flange)',
    fluidMode: 'internal_cross_drilled',
    fluidModeLabel: 'Internal Rifle-Drilled Gallery (No External Hoses)',
    sprayPattern: 'flat_fan',
    sprayPatternLabel: 'Opposed Precision Flat-Fan (Fixed & Moving Die)',
    coverageWidthMm: 380,
    adjustability: 'fixed_drilled',
    adjustabilityLabel: 'Factory Fixed Bored Ports (Zero Creep Under Vibration)',
    nozzleAdjustabilityDetails: 'Fixed machined ports at factory engineered coordinates. Zero mechanical creep, no loosening screws under aggressive robot accelerations.',
    nozzleCount: 10,
    nozzleLayout: 'Dual-Row Opposing Fixed (5 Fixed / 5 Moving, plus integrated air-knife slit)',
    operatingPressureBar: {
      lubeMin: 3.0,
      lubeMax: 6.0,
      airMin: 4.5,
      airMax: 7.0
    },
    fluidAirSupply: {
      lubePressure: '3.0 - 6.0 bar (Medium Pressure Diluted Release Agent)',
      airPressure: '4.5 - 7.0 bar (Dry Shop Air for Atomization & Air Blow)',
      lubeFlowRate: '35 - 75 mL/sec total manifold flow',
      airConsumptionNlPerMin: 1450,
      connectionInterfaces: '1x G 3/8" Lube In, 1x G 1/2" Atomizing Air, 1x G 1/2" Main Blast Air'
    },
    cycleTimeAdvantageSec: 2.8,
    cycleTimeNote: '2.5 - 3.2s faster per cycle due to simultaneous dual-face spraying and higher wrist acceleration with rigid monoblock.',
    costTier: 'PREMIUM',
    costTierLabel: '$$$ Premium Machined Billet',
    maintenanceComplexity: 'LOW',
    maintenanceNotes: 'Ultra-low maintenance: No external hose bundles to tear or leak. Flush manifold channel monthly with descaler.',
    keyFeatures: [
      'Monolithic CNC 6061-T6 billet aluminum construction',
      'Gun-drilled internal fluid galleries eliminate external hose-pinch risks',
      'Dual opposing spray faces for simultaneous cover/ejector die coverage',
      'Integrated high-velocity air-knife slit for rapid parting line drying',
      'Rigid ISO 9409-1 direct mounting flange with zero dynamic deflection'
    ],
    recommendedDcmRangeTons: [350, 1350],
    defaultSprayDistanceMm: 130,
    dropletSizeUm: 45,
    lubeSavingsPercent: 15,
    nozzles: [
      { id: 'mb-f1', name: 'Fixed Side Top Left', offsetMm: [-110, 40, 35], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 },
      { id: 'mb-f2', name: 'Fixed Side Top Right', offsetMm: [110, 40, 35], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 },
      { id: 'mb-f3', name: 'Fixed Side Center Hub', offsetMm: [0, 0, 35], directionVector: [0, 0, -1], sprayAngleDeg: 70, type: 'lube', flowRatio: 1.2, sprayWidthMm: 200 },
      { id: 'mb-f4', name: 'Fixed Side Bottom Left', offsetMm: [-110, -40, 35], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 },
      { id: 'mb-f5', name: 'Fixed Side Bottom Right', offsetMm: [110, -40, 35], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 },
      { id: 'mb-m1', name: 'Moving Side Top Left', offsetMm: [-110, 40, -35], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 },
      { id: 'mb-m2', name: 'Moving Side Top Right', offsetMm: [110, 40, -35], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 },
      { id: 'mb-m3', name: 'Moving Side Center Hub', offsetMm: [0, 0, -35], directionVector: [0, 0, 1], sprayAngleDeg: 70, type: 'lube', flowRatio: 1.2, sprayWidthMm: 200 },
      { id: 'mb-m4', name: 'Moving Side Bottom Left', offsetMm: [-110, -40, -35], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 },
      { id: 'mb-m5', name: 'Moving Side Bottom Right', offsetMm: [110, -40, -35], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 }
    ]
  },
  {
    id: 'MODULAR',
    type: 'MODULAR',
    name: 'Modular Rail Framework EOAT',
    subtitle: 'Extruded T-Slot Rails • Articulated Extension Wands',
    category: 'Flexible Job-Shop Tooling',
    description: 'Rail/framework manifold with independently adjustable nozzle blocks, rigid extension tubes, multi-axis swivel joints, mounting brackets, and visible polyurethane hoses with push-in fittings. Fully reconfigurable for rapid die changeovers and custom cavity geometry.',
    weightKg: 19.8,
    dimensionsMm: {
      width: 480,
      height: 240,
      depth: 150,
      clearanceRadius: 280
    },
    mountingInterface: 'ISO 9409-1-100-6-M8 with Quick-Clamp Stem',
    fluidMode: 'modular_twin_fluid',
    fluidModeLabel: 'External Multi-Circuit Tubing with Quick-Fit Swivels',
    sprayPattern: 'full_cone',
    sprayPatternLabel: 'Independently Articulated Targeted Cones & Deep Lances',
    coverageWidthMm: 520,
    adjustability: 'independently_adjustable',
    adjustabilityLabel: '3-Axis Slide & Swivel Joints (User Configurable)',
    nozzleAdjustabilityDetails: 'Independently sliding rail clamp blocks (X-axis ±200mm, Y-axis ±80mm) with ±35° ball-swivel knuckles for custom cavity contours.',
    nozzleCount: 14,
    nozzleLayout: 'Articulated T-Slot Clustered Array (7 Fixed / 7 Moving including deep-lance extensions)',
    operatingPressureBar: {
      lubeMin: 2.5,
      lubeMax: 5.5,
      airMin: 4.0,
      airMax: 6.5
    },
    fluidAirSupply: {
      lubePressure: '2.5 - 5.5 bar (Adjustable Fluid Regulator)',
      airPressure: '4.0 - 6.5 bar (Main Blast & Swivel Assist Air)',
      lubeFlowRate: '45 - 90 mL/sec total manifold flow',
      airConsumptionNlPerMin: 1900,
      connectionInterfaces: 'Central distribution block with 8mm OD polyurethane push-in pneumatic/fluid lines'
    },
    cycleTimeAdvantageSec: 1.2,
    cycleTimeNote: 'Enables complex multi-cavity reach without extra robot re-orientations; ~1.2s savings on deep die designs.',
    costTier: 'MID_RANGE',
    costTierLabel: '$$ Cost-Effective Modular Framework',
    maintenanceComplexity: 'MEDIUM',
    maintenanceNotes: 'Inspect swivel joints and hose fittings weekly for seal integrity or flex fatigue. Replace push-in O-rings semi-annually.',
    keyFeatures: [
      'Dual 40x40 structural extruded aluminum profile rails',
      'Independently sliding clamp carriages with brass lock screws',
      'Articulating stainless extension wands for deep cavity core reach',
      'Ball-swivel nozzle heads with ±35° multi-axis directional tilt',
      'Color-coded polyurethane twin-fluid hoses with push-in fittings'
    ],
    recommendedDcmRangeTons: [500, 2000],
    defaultSprayDistanceMm: 150,
    dropletSizeUm: 55,
    lubeSavingsPercent: 20,
    nozzles: [
      { id: 'mod-1', name: 'Lance Left Top (Fixed)', offsetMm: [-160, 80, 50], directionVector: [0.1, 0, -1], sprayAngleDeg: 60, type: 'combined', flowRatio: 1.1, sprayWidthMm: 160, isAdjustable: true, swivelAngleDeg: 15 },
      { id: 'mod-2', name: 'Lance Center Top (Fixed)', offsetMm: [0, 80, 50], directionVector: [0, 0, -1], sprayAngleDeg: 60, type: 'combined', flowRatio: 1.0, sprayWidthMm: 160, isAdjustable: true },
      { id: 'mod-3', name: 'Lance Right Top (Fixed)', offsetMm: [160, 80, 50], directionVector: [-0.1, 0, -1], sprayAngleDeg: 60, type: 'combined', flowRatio: 1.1, sprayWidthMm: 160, isAdjustable: true, swivelAngleDeg: -15 },
      { id: 'mod-4', name: 'Core Blast Left (Fixed)', offsetMm: [-100, 0, 70], directionVector: [0, 0, -1], sprayAngleDeg: 50, type: 'lube', flowRatio: 1.3, sprayWidthMm: 140, isAdjustable: true },
      { id: 'mod-5', name: 'Core Blast Right (Fixed)', offsetMm: [100, 0, 70], directionVector: [0, 0, -1], sprayAngleDeg: 50, type: 'lube', flowRatio: 1.3, sprayWidthMm: 140, isAdjustable: true },
      { id: 'mod-6', name: 'Slide Air Jet (Fixed)', offsetMm: [0, -70, 40], directionVector: [0, 0.2, -1], sprayAngleDeg: 75, type: 'air', flowRatio: 1.0, sprayWidthMm: 220, isAdjustable: true },
      { id: 'mod-7', name: 'Bottom Chiller (Fixed)', offsetMm: [-140, -80, 40], directionVector: [0.1, 0.2, -1], sprayAngleDeg: 60, type: 'combined', flowRatio: 1.1, sprayWidthMm: 160, isAdjustable: true },
      { id: 'mod-8', name: 'Lance Left Top (Moving)', offsetMm: [-160, 80, -50], directionVector: [0.1, 0, 1], sprayAngleDeg: 60, type: 'combined', flowRatio: 1.1, sprayWidthMm: 160, isAdjustable: true, swivelAngleDeg: 15 },
      { id: 'mod-9', name: 'Lance Center Top (Moving)', offsetMm: [0, 80, -50], directionVector: [0, 0, 1], sprayAngleDeg: 60, type: 'combined', flowRatio: 1.0, sprayWidthMm: 160, isAdjustable: true },
      { id: 'mod-10', name: 'Lance Right Top (Moving)', offsetMm: [160, 80, -50], directionVector: [-0.1, 0, 1], sprayAngleDeg: 60, type: 'combined', flowRatio: 1.1, sprayWidthMm: 160, isAdjustable: true, swivelAngleDeg: -15 },
      { id: 'mod-11', name: 'Core Blast Left (Moving)', offsetMm: [-100, 0, -70], directionVector: [0, 0, 1], sprayAngleDeg: 50, type: 'lube', flowRatio: 1.3, sprayWidthMm: 140, isAdjustable: true },
      { id: 'mod-12', name: 'Core Blast Right (Moving)', offsetMm: [100, 0, -70], directionVector: [0, 0, 1], sprayAngleDeg: 50, type: 'lube', flowRatio: 1.3, sprayWidthMm: 140, isAdjustable: true },
      { id: 'mod-13', name: 'Slide Air Jet (Moving)', offsetMm: [0, -70, -40], directionVector: [0, 0.2, 1], sprayAngleDeg: 75, type: 'air', flowRatio: 1.0, sprayWidthMm: 220, isAdjustable: true },
      { id: 'mod-14', name: 'Bottom Chiller (Moving)', offsetMm: [140, -80, -40], directionVector: [-0.1, 0.2, 1], sprayAngleDeg: 60, type: 'combined', flowRatio: 1.1, sprayWidthMm: 160, isAdjustable: true }
    ]
  },
  {
    id: 'MATRIX',
    type: 'MATRIX',
    name: 'Matrix Planar Grid Array EOAT',
    subtitle: 'Large Uniform Nozzle Grid • Structural & Giga-Castings',
    category: 'Large-Die & Structural Casting Tooling',
    description: 'Large flat grid/array of standardized twin-fluid nozzles engineered for broad die surfaces, automotive shock towers, subframes, and structural giga-castings. Provides instant wide-area coverage with dense uniform nozzle layout and heavy-duty fluid supply trunks.',
    weightKg: 28.5,
    dimensionsMm: {
      width: 640,
      height: 420,
      depth: 110,
      clearanceRadius: 380
    },
    mountingInterface: 'ISO 9409-1-125-6-M10 (Heavy-Duty Industrial Flange)',
    fluidMode: 'matrix_array',
    fluidModeLabel: 'High-Volume Dual Plenum Distribution Trunk',
    sprayPattern: 'wide_matrix',
    sprayPatternLabel: 'High-Density Uniform Planar Matrix Array',
    coverageWidthMm: 720,
    adjustability: 'fixed_grid',
    adjustabilityLabel: 'Factory Calibrated High-Density Grid (Multi-Zone Valving)',
    nozzleAdjustabilityDetails: 'Uniform high-density fixed matrix with multi-zone pneumatic shutoff bank (Zone A/B/C selectable in robot program).',
    nozzleCount: 24,
    nozzleLayout: 'Uniform 6x4 Planar Grid Array (12 Fixed Die / 12 Moving Die Nozzles, 24 total)',
    operatingPressureBar: {
      lubeMin: 3.5,
      lubeMax: 7.0,
      airMin: 5.0,
      airMax: 8.0
    },
    fluidAirSupply: {
      lubePressure: '3.5 - 7.0 bar (High Flow Dual Header Distribution)',
      airPressure: '5.0 - 8.0 bar (Dedicated High-Volume Air Reservoir Required)',
      lubeFlowRate: '80 - 180 mL/sec total matrix flow',
      airConsumptionNlPerMin: 3800,
      connectionInterfaces: 'Dual G 3/4" high-flow braided stainless umbilicals with quick-disconnect coupling'
    },
    cycleTimeAdvantageSec: 5.4,
    cycleTimeNote: 'Up to 5.5s cycle time reduction on large structural dies. Covers entire die envelope in 1-2 rapid sweeps instead of raster passes.',
    costTier: 'HIGH_END',
    costTierLabel: '$$$$ High-End Large Envelope Tooling',
    maintenanceComplexity: 'MEDIUM',
    maintenanceNotes: 'Daily ultrasonic nozzle check. Requires high-capacity plant air compressor reservoir (≥4 m³/min).',
    keyFeatures: [
      'Full 6x4 standardized twin-fluid nozzle array (12 fixed / 12 moving)',
      'Instantaneous broad-envelope coverage reduces robot dwell time by 45%',
      'Ribbed structural perimeter frame with high torsional stiffness',
      'Dual-circuit high-flow supply headers with pressure transducers',
      'Ideal for battery trays, shock towers, longitudinal rails, and giga-press dies'
    ],
    recommendedDcmRangeTons: [800, 3500],
    defaultSprayDistanceMm: 160,
    dropletSizeUm: 50,
    lubeSavingsPercent: 25,
    nozzles: [
      // 12 Fixed Face Nozzles (3 rows x 4 cols)
      { id: 'mat-f1', name: 'Fixed Row 1 Col 1', offsetMm: [-220, 130, 40], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 170 },
      { id: 'mat-f2', name: 'Fixed Row 1 Col 2', offsetMm: [-75, 130, 40], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 170 },
      { id: 'mat-f3', name: 'Fixed Row 1 Col 3', offsetMm: [75, 130, 40], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 170 },
      { id: 'mat-f4', name: 'Fixed Row 1 Col 4', offsetMm: [220, 130, 40], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 170 },
      { id: 'mat-f5', name: 'Fixed Row 2 Col 1', offsetMm: [-220, 0, 40], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 170 },
      { id: 'mat-f6', name: 'Fixed Row 2 Col 2', offsetMm: [-75, 0, 40], directionVector: [0, 0, -1], sprayAngleDeg: 70, type: 'lube', flowRatio: 1.2, sprayWidthMm: 180 },
      { id: 'mat-f7', name: 'Fixed Row 2 Col 3', offsetMm: [75, 0, 40], directionVector: [0, 0, -1], sprayAngleDeg: 70, type: 'lube', flowRatio: 1.2, sprayWidthMm: 180 },
      { id: 'mat-f8', name: 'Fixed Row 2 Col 4', offsetMm: [220, 0, 40], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 170 },
      { id: 'mat-f9', name: 'Fixed Row 3 Col 1', offsetMm: [-220, -130, 40], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 170 },
      { id: 'mat-f10', name: 'Fixed Row 3 Col 2', offsetMm: [-75, -130, 40], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 170 },
      { id: 'mat-f11', name: 'Fixed Row 3 Col 3', offsetMm: [75, -130, 40], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 170 },
      { id: 'mat-f12', name: 'Fixed Row 3 Col 4', offsetMm: [220, -130, 40], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 170 },
      // 12 Moving Face Nozzles (3 rows x 4 cols)
      { id: 'mat-m1', name: 'Moving Row 1 Col 1', offsetMm: [-220, 130, -40], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 170 },
      { id: 'mat-m2', name: 'Moving Row 1 Col 2', offsetMm: [-75, 130, -40], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 170 },
      { id: 'mat-m3', name: 'Moving Row 1 Col 3', offsetMm: [75, 130, -40], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 170 },
      { id: 'mat-m4', name: 'Moving Row 1 Col 4', offsetMm: [220, 130, -40], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 170 },
      { id: 'mat-m5', name: 'Moving Row 2 Col 1', offsetMm: [-220, 0, -40], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 170 },
      { id: 'mat-m6', name: 'Moving Row 2 Col 2', offsetMm: [-75, 0, -40], directionVector: [0, 0, 1], sprayAngleDeg: 70, type: 'lube', flowRatio: 1.2, sprayWidthMm: 180 },
      { id: 'mat-m7', name: 'Moving Row 2 Col 3', offsetMm: [75, 0, -40], directionVector: [0, 0, 1], sprayAngleDeg: 70, type: 'lube', flowRatio: 1.2, sprayWidthMm: 180 },
      { id: 'mat-m8', name: 'Moving Row 2 Col 4', offsetMm: [220, 0, -40], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 170 },
      { id: 'mat-m9', name: 'Moving Row 3 Col 1', offsetMm: [-220, -130, -40], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 170 },
      { id: 'mat-m10', name: 'Moving Row 3 Col 2', offsetMm: [-75, -130, -40], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 170 },
      { id: 'mat-m11', name: 'Moving Row 3 Col 3', offsetMm: [75, -130, -40], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 170 },
      { id: 'mat-m12', name: 'Moving Row 3 Col 4', offsetMm: [220, -130, -40], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 170 }
    ]
  },
  {
    id: 'MICRO_DOSING',
    type: 'MICRO_DOSING',
    name: 'Micro-Dosing / MQL Precision EOAT',
    subtitle: 'Zero-Drip High-Speed Pulse Micro-Valves • Concentrate Spray',
    category: 'Minimum Quantity Lubrication (MQL)',
    description: 'Compact precision manifold with specialized high-speed pulse micro-valves for minimal lubricant consumption, zero-drip suck-back anti-clog technology, and high-frequency pulse spraying. Delivers ultra-fine aerosol mist (15-30 µm) with up to 90% water and lubricant savings.',
    weightKg: 7.2,
    dimensionsMm: {
      width: 260,
      height: 110,
      depth: 75,
      clearanceRadius: 150
    },
    mountingInterface: 'ISO 9409-1-63-4-M6 / ISO 9409-1-100-6-M8 (Ultra-Light Flange)',
    fluidMode: 'mql_micro_pulse',
    fluidModeLabel: 'High-Frequency Pulse Micro-Dosing (Pure Concentrate)',
    sprayPattern: 'micro_aerosol_pulse',
    sprayPatternLabel: 'Aerosol Micro-Droplet Mist (15-30 µm, Zero Overspray)',
    coverageWidthMm: 280,
    adjustability: 'precision_fixed',
    adjustabilityLabel: 'Micrometer Flow Metering per Valve (Zero Droplet Runoff)',
    nozzleAdjustabilityDetails: 'Precision micrometer needle valve stroke adjustments (0.01 - 0.25 mL per pulse) with individual electronic PWM control.',
    nozzleCount: 8,
    nozzleLayout: 'High-Precision Linear Micro-Injectors (4 Fixed / 4 Moving with suck-back valves)',
    operatingPressureBar: {
      lubeMin: 6.0,
      lubeMax: 15.0,
      airMin: 4.0,
      airMax: 6.5
    },
    fluidAirSupply: {
      lubePressure: '6.0 - 15.0 bar (Pure Concentrate Release Agent / MQL)',
      airPressure: '4.0 - 6.5 bar (Precision Low-Flow Micro-Atomization)',
      lubeFlowRate: '4 - 18 mL/sec (Sub-milliliter pulsed dosing)',
      airConsumptionNlPerMin: 620,
      connectionInterfaces: 'Micro-bore 4mm stainless steel fluid tubing and 24V DC M12 electrical solenoid bus'
    },
    cycleTimeAdvantageSec: 3.6,
    cycleTimeNote: 'Saves 3.5 - 4.2s per cycle because dry time is near zero (no water puddle evaporation needed). Parting line remains dry.',
    costTier: 'HIGH_END',
    costTierLabel: '$$$$ Precision MQL Technology',
    maintenanceComplexity: 'HIGH',
    maintenanceNotes: 'Micro-filtration (≤10 micron) strictly required. Monthly solenoid seal inspection. Zero effluent disposal cost.',
    keyFeatures: [
      'Piezoelectric/high-speed solenoid micro-pulse valves (up to 50 Hz)',
      'Active suck-back anti-drip chamber eliminates parting-line drips',
      'Ultra-light 7.2kg payload maximizes robot wrist acceleration and reach',
      'Reduces fluid consumption by 85-90% with zero wastewater effluent',
      'Fine sub-30 µm atomization eliminates die thermal fatigue and crazing'
    ],
    recommendedDcmRangeTons: [250, 1600],
    defaultSprayDistanceMm: 110,
    dropletSizeUm: 22,
    lubeSavingsPercent: 88,
    nozzles: [
      { id: 'mql-f1', name: 'Micro Injector F1 (Left)', offsetMm: [-80, 25, 25], directionVector: [0, 0, -1], sprayAngleDeg: 45, type: 'lube', flowRatio: 0.8, sprayWidthMm: 110 },
      { id: 'mql-f2', name: 'Micro Injector F2 (Center-Left)', offsetMm: [-25, 25, 25], directionVector: [0, 0, -1], sprayAngleDeg: 45, type: 'lube', flowRatio: 0.8, sprayWidthMm: 110 },
      { id: 'mql-f3', name: 'Micro Injector F3 (Center-Right)', offsetMm: [25, 25, 25], directionVector: [0, 0, -1], sprayAngleDeg: 45, type: 'lube', flowRatio: 0.8, sprayWidthMm: 110 },
      { id: 'mql-f4', name: 'Micro Injector F4 (Right)', offsetMm: [80, 25, 25], directionVector: [0, 0, -1], sprayAngleDeg: 45, type: 'lube', flowRatio: 0.8, sprayWidthMm: 110 },
      { id: 'mql-m1', name: 'Micro Injector M1 (Left)', offsetMm: [-80, -25, -25], directionVector: [0, 0, 1], sprayAngleDeg: 45, type: 'lube', flowRatio: 0.8, sprayWidthMm: 110 },
      { id: 'mql-m2', name: 'Micro Injector M2 (Center-Left)', offsetMm: [-25, -25, -25], directionVector: [0, 0, 1], sprayAngleDeg: 45, type: 'lube', flowRatio: 0.8, sprayWidthMm: 110 },
      { id: 'mql-m3', name: 'Micro Injector M3 (Center-Right)', offsetMm: [25, -25, -25], directionVector: [0, 0, 1], sprayAngleDeg: 45, type: 'lube', flowRatio: 0.8, sprayWidthMm: 110 },
      { id: 'mql-m4', name: 'Micro Injector M4 (Right)', offsetMm: [80, -25, -25], directionVector: [0, 0, 1], sprayAngleDeg: 45, type: 'lube', flowRatio: 0.8, sprayWidthMm: 110 }
    ]
  }
];

export const SPRAY_HEAD_PRESETS: SprayHeadPreset[] = [
  // Primary 4 Realistic EOAT Tooling Options
  {
    id: 'MONOBLOCK',
    name: EOAT_PRESETS[0].name,
    category: EOAT_PRESETS[0].category,
    description: EOAT_PRESETS[0].description,
    manifoldType: 'monoblock',
    manifoldWidthMm: EOAT_PRESETS[0].dimensionsMm.width,
    nozzleCount: EOAT_PRESETS[0].nozzleCount,
    weightKg: EOAT_PRESETS[0].weightKg,
    defaultSprayDistanceMm: EOAT_PRESETS[0].defaultSprayDistanceMm,
    nozzles: EOAT_PRESETS[0].nozzles,
    eoatSpec: EOAT_PRESETS[0]
  },
  {
    id: 'MODULAR',
    name: EOAT_PRESETS[1].name,
    category: EOAT_PRESETS[1].category,
    description: EOAT_PRESETS[1].description,
    manifoldType: 'modular_frame',
    manifoldWidthMm: EOAT_PRESETS[1].dimensionsMm.width,
    nozzleCount: EOAT_PRESETS[1].nozzleCount,
    weightKg: EOAT_PRESETS[1].weightKg,
    defaultSprayDistanceMm: EOAT_PRESETS[1].defaultSprayDistanceMm,
    nozzles: EOAT_PRESETS[1].nozzles,
    eoatSpec: EOAT_PRESETS[1]
  },
  {
    id: 'MATRIX',
    name: EOAT_PRESETS[2].name,
    category: EOAT_PRESETS[2].category,
    description: EOAT_PRESETS[2].description,
    manifoldType: 'matrix_grid',
    manifoldWidthMm: EOAT_PRESETS[2].dimensionsMm.width,
    nozzleCount: EOAT_PRESETS[2].nozzleCount,
    weightKg: EOAT_PRESETS[2].weightKg,
    defaultSprayDistanceMm: EOAT_PRESETS[2].defaultSprayDistanceMm,
    nozzles: EOAT_PRESETS[2].nozzles,
    eoatSpec: EOAT_PRESETS[2]
  },
  {
    id: 'MICRO_DOSING',
    name: EOAT_PRESETS[3].name,
    category: EOAT_PRESETS[3].category,
    description: EOAT_PRESETS[3].description,
    manifoldType: 'micro_dosing',
    manifoldWidthMm: EOAT_PRESETS[3].dimensionsMm.width,
    nozzleCount: EOAT_PRESETS[3].nozzleCount,
    weightKg: EOAT_PRESETS[3].weightKg,
    defaultSprayDistanceMm: EOAT_PRESETS[3].defaultSprayDistanceMm,
    nozzles: EOAT_PRESETS[3].nozzles,
    eoatSpec: EOAT_PRESETS[3],
    microSpraySettings: {
      fineSpray: true,
      sprayWidthMm: 110,
      applicationRateMlPerSec: 15
    }
  },
  // Legacy / Alternate Presets
  {
    id: 'dual_sided',
    name: 'Dual-Sided / Multi-Directional Head',
    category: 'Double-Acting Matrix',
    description: 'Compact spray head with opposed nozzles facing Fixed and Moving die faces simultaneously. Eliminates excessive wrist twisting in daylight.',
    manifoldType: 'dual_sided_matrix',
    manifoldWidthMm: 280,
    nozzleCount: 8,
    weightKg: 14.5,
    defaultSprayDistanceMm: 140,
    nozzles: [
      { id: 'nz-f1', name: 'Fixed Side Top Left', offsetMm: [-100, 40, 20], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 },
      { id: 'nz-f2', name: 'Fixed Side Top Right', offsetMm: [100, 40, 20], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 },
      { id: 'nz-f3', name: 'Fixed Side Bottom Left', offsetMm: [-100, -40, 20], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 },
      { id: 'nz-f4', name: 'Fixed Side Bottom Right', offsetMm: [100, -40, 20], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 },
      { id: 'nz-m1', name: 'Moving Side Top Left', offsetMm: [-100, 40, -20], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 },
      { id: 'nz-m2', name: 'Moving Side Top Right', offsetMm: [100, 40, -20], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 },
      { id: 'nz-m3', name: 'Moving Side Bottom Left', offsetMm: [-100, -40, -20], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 },
      { id: 'nz-m4', name: 'Moving Side Bottom Right', offsetMm: [100, -40, -20], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 }
    ]
  },
  {
    id: 'contour_frame',
    name: 'Contour / Picture-Frame Head',
    category: 'Perimeter Manifold',
    description: 'Conformal rectangular perimeter manifold following die parting line geometry. Delivers uniform enveloping coverage with minimal robot motion.',
    manifoldType: 'multi_head_linear',
    manifoldWidthMm: 420,
    nozzleCount: 12,
    weightKg: 21.0,
    defaultSprayDistanceMm: 160,
    nozzles: [
      { id: 'nz-c1', name: 'Top Left Rim', offsetMm: [-180, 120, 0], directionVector: [0.2, -0.2, -1], sprayAngleDeg: 70, type: 'combined', flowRatio: 1.1, sprayWidthMm: 220 },
      { id: 'nz-c2', name: 'Top Center Rim', offsetMm: [0, 120, 0], directionVector: [0, -0.2, -1], sprayAngleDeg: 70, type: 'combined', flowRatio: 1.0, sprayWidthMm: 220 },
      { id: 'nz-c3', name: 'Top Right Rim', offsetMm: [180, 120, 0], directionVector: [-0.2, -0.2, -1], sprayAngleDeg: 70, type: 'combined', flowRatio: 1.1, sprayWidthMm: 220 },
      { id: 'nz-c4', name: 'Bottom Left Rim', offsetMm: [-180, -120, 0], directionVector: [0.2, 0.2, -1], sprayAngleDeg: 70, type: 'combined', flowRatio: 1.1, sprayWidthMm: 220 },
      { id: 'nz-c5', name: 'Bottom Center Rim', offsetMm: [0, -120, 0], directionVector: [0, 0.2, -1], sprayAngleDeg: 70, type: 'combined', flowRatio: 1.0, sprayWidthMm: 220 },
      { id: 'nz-c6', name: 'Bottom Right Rim', offsetMm: [180, -120, 0], directionVector: [-0.2, 0.2, -1], sprayAngleDeg: 70, type: 'combined', flowRatio: 1.1, sprayWidthMm: 220 }
    ]
  },
  {
    id: 'modular_extension',
    name: 'Modular Extension Head (Deep Cavity)',
    category: 'Articulated Wands',
    description: 'Equipped with extended articulating copper/titanium lance tubes for reaching deep core cavities, slides, and tight tie-bar daylight.',
    manifoldType: 'multi_head_linear',
    manifoldWidthMm: 240,
    nozzleCount: 6,
    weightKg: 12.0,
    defaultSprayDistanceMm: 120,
    nozzles: [
      { id: 'nz-e1', name: 'Deep Well Lance 1', offsetMm: [-60, 0, 120], directionVector: [0, 0, -1], sprayAngleDeg: 55, type: 'lube', flowRatio: 1.3, sprayWidthMm: 140 },
      { id: 'nz-e2', name: 'Deep Well Lance 2', offsetMm: [60, 0, 120], directionVector: [0, 0, -1], sprayAngleDeg: 55, type: 'lube', flowRatio: 1.3, sprayWidthMm: 140 },
      { id: 'nz-e3', name: 'Core Pin Blast', offsetMm: [0, 50, 80], directionVector: [0, -0.3, -1], sprayAngleDeg: 50, type: 'air', flowRatio: 1.0, sprayWidthMm: 120 },
      { id: 'nz-e4', name: 'Slide Face Nozzle', offsetMm: [0, -50, 80], directionVector: [0, 0.3, -1], sprayAngleDeg: 50, type: 'air', flowRatio: 1.0, sprayWidthMm: 120 }
    ]
  },
  {
    id: 'micro_spray',
    name: 'Micro-Spray / MQL Precision Head',
    category: 'Minimum Quantity Lubrication',
    description: 'High-frequency pulsing micro-dosing valves. Generates fine aerosol mist (15-35 µm) with 90% water reduction and near-zero effluent.',
    manifoldType: 'micro_spray',
    manifoldWidthMm: 200,
    nozzleCount: 6,
    weightKg: 8.5,
    defaultSprayDistanceMm: 110,
    microSpraySettings: {
      fineSpray: true,
      sprayWidthMm: 110,
      applicationRateMlPerSec: 18
    },
    nozzles: [
      { id: 'nz-mql1', name: 'Micro Injector L1', offsetMm: [-60, 20, 0], directionVector: [0, 0, -1], sprayAngleDeg: 45, type: 'lube', flowRatio: 0.8, sprayWidthMm: 110 },
      { id: 'nz-mql2', name: 'Micro Injector C1', offsetMm: [0, 20, 0], directionVector: [0, 0, -1], sprayAngleDeg: 45, type: 'lube', flowRatio: 0.8, sprayWidthMm: 110 },
      { id: 'nz-mql3', name: 'Micro Injector R1', offsetMm: [60, 20, 0], directionVector: [0, 0, -1], sprayAngleDeg: 45, type: 'lube', flowRatio: 0.8, sprayWidthMm: 110 },
      { id: 'nz-mql4', name: 'Micro Injector L2', offsetMm: [-60, -20, 0], directionVector: [0, 0, 1], sprayAngleDeg: 45, type: 'lube', flowRatio: 0.8, sprayWidthMm: 110 },
      { id: 'nz-mql5', name: 'Micro Injector C2', offsetMm: [0, -20, 0], directionVector: [0, 0, 1], sprayAngleDeg: 45, type: 'lube', flowRatio: 0.8, sprayWidthMm: 110 },
      { id: 'nz-mql6', name: 'Micro Injector R2', offsetMm: [60, -20, 0], directionVector: [0, 0, 1], sprayAngleDeg: 45, type: 'lube', flowRatio: 0.8, sprayWidthMm: 110 }
    ]
  },
  {
    id: 'conventional_water',
    name: 'Conventional Water-Based Spray Head',
    category: 'High-Volume Emulsion',
    description: 'Robust external-mix twin-fluid block. Provides intensive cooling for high-thermal alloys, thick biscuits, and heavy runner junctions.',
    manifoldType: 'dual_sided_matrix',
    manifoldWidthMm: 320,
    nozzleCount: 10,
    weightKg: 16.5,
    defaultSprayDistanceMm: 160,
    conventionalSettings: {
      liquidFlowMlPerSec: 65,
      airPressureBar: 5.5,
      sprayWidthMm: 220
    },
    nozzles: [
      { id: 'nz-w1', name: 'Cooling Wash Front 1', offsetMm: [-80, 40, 10], directionVector: [0, 0, -1], sprayAngleDeg: 75, type: 'combined', flowRatio: 1.2, sprayWidthMm: 220 },
      { id: 'nz-w2', name: 'Cooling Wash Front 2', offsetMm: [80, 40, 10], directionVector: [0, 0, -1], sprayAngleDeg: 75, type: 'combined', flowRatio: 1.2, sprayWidthMm: 220 },
      { id: 'nz-w3', name: 'Air Blow Jet Front 1', offsetMm: [-80, -40, 10], directionVector: [0, 0, -1], sprayAngleDeg: 80, type: 'air', flowRatio: 1.0, sprayWidthMm: 240 },
      { id: 'nz-w4', name: 'Air Blow Jet Front 2', offsetMm: [80, -40, 10], directionVector: [0, 0, -1], sprayAngleDeg: 80, type: 'air', flowRatio: 1.0, sprayWidthMm: 240 },
      { id: 'nz-w5', name: 'Cooling Wash Rear 1', offsetMm: [-80, 40, -10], directionVector: [0, 0, 1], sprayAngleDeg: 75, type: 'combined', flowRatio: 1.2, sprayWidthMm: 220 },
      { id: 'nz-w6', name: 'Cooling Wash Rear 2', offsetMm: [80, 40, -10], directionVector: [0, 0, 1], sprayAngleDeg: 75, type: 'combined', flowRatio: 1.2, sprayWidthMm: 220 },
      { id: 'nz-w7', name: 'Air Blow Jet Rear 1', offsetMm: [-80, -40, -10], directionVector: [0, 0, 1], sprayAngleDeg: 80, type: 'air', flowRatio: 1.0, sprayWidthMm: 240 },
      { id: 'nz-w8', name: 'Air Blow Jet Rear 2', offsetMm: [80, -40, -10], directionVector: [0, 0, 1], sprayAngleDeg: 80, type: 'air', flowRatio: 1.0, sprayWidthMm: 240 }
    ]
  },
  {
    id: 'hybrid_head',
    name: 'Hybrid Micro + Cooling Blast Head',
    category: 'Dual Circuit System',
    description: 'Dual-circuit system combining micro-spray release film deposition with targeted high-flow cooling blowers for hot spots.',
    manifoldType: 'dual_sided_matrix',
    manifoldWidthMm: 300,
    nozzleCount: 8,
    weightKg: 15.0,
    defaultSprayDistanceMm: 135,
    nozzles: [
      { id: 'nz-hy1', name: 'Cavity Micro Nozzle 1', offsetMm: [-70, 25, 0], directionVector: [0, 0, -1], sprayAngleDeg: 55, type: 'lube', flowRatio: 0.9, sprayWidthMm: 150 },
      { id: 'nz-hy2', name: 'Cavity Micro Nozzle 2', offsetMm: [70, 25, 0], directionVector: [0, 0, -1], sprayAngleDeg: 55, type: 'lube', flowRatio: 0.9, sprayWidthMm: 150 },
      { id: 'nz-hy3', name: 'Biscuit High-Flow Chiller', offsetMm: [0, -40, 0], directionVector: [0, 0, -1], sprayAngleDeg: 85, type: 'combined', flowRatio: 1.6, sprayWidthMm: 250 },
      { id: 'nz-hy4', name: 'Core Drying Air Knife', offsetMm: [0, 50, 0], directionVector: [0, 0, 1], sprayAngleDeg: 90, type: 'air', flowRatio: 1.2, sprayWidthMm: 280 }
    ]
  }
];

export const DEFAULT_HOTSPOTS: HotSpotDefinition[] = [
  {
    id: 'hs-biscuit',
    name: 'Biscuit & Injection Sleeve Hub',
    type: 'biscuit',
    location: [0, -220, -120],
    thermalPriority: 'VERY HOT',
    extraCoolingRequired: true,
    extraPasses: 2,
    slowerSpeedFactor: 0.6,
    surfaceAreaMm2: 9500
  },
  {
    id: 'hs-runner',
    name: 'Main Gate & Ingate Runner',
    type: 'main_gate',
    location: [0, -150, -40],
    thermalPriority: 'HOT',
    extraCoolingRequired: true,
    extraPasses: 1,
    slowerSpeedFactor: 0.75,
    surfaceAreaMm2: 6800
  },
  {
    id: 'hs-corepin',
    name: 'Slender Core Pin Tip',
    type: 'core_pin',
    location: [90, 140, 60],
    thermalPriority: 'VERY HOT',
    extraCoolingRequired: true,
    extraPasses: 2,
    slowerSpeedFactor: 0.5,
    surfaceAreaMm2: 3200
  },
  {
    id: 'hs-thickboss',
    name: 'Bearing Boss Heavy Section',
    type: 'thick_section',
    location: [-80, 20, -50],
    thermalPriority: 'HOT',
    extraCoolingRequired: false,
    extraPasses: 1,
    slowerSpeedFactor: 0.8,
    surfaceAreaMm2: 8400
  }
];

export const TOOL_DEFAULT: ToolCenterPoint = {
  x: 0,
  y: 0,
  z: 220,
  rx: 0,
  ry: 0,
  rz: 0,
  manifoldType: 'monoblock',
  sprayHeadType: 'MONOBLOCK',
  eoatType: 'MONOBLOCK',
  eoatSpec: EOAT_PRESETS[0],
  nozzleCount: EOAT_PRESETS[0].nozzleCount,
  manifoldWidthMm: EOAT_PRESETS[0].dimensionsMm.width,
  weightKg: EOAT_PRESETS[0].weightKg,
  dimensions: {
    width: EOAT_PRESETS[0].dimensionsMm.width,
    height: EOAT_PRESETS[0].dimensionsMm.height,
    depth: EOAT_PRESETS[0].dimensionsMm.depth,
    clearanceRadius: EOAT_PRESETS[0].dimensionsMm.clearanceRadius
  },
  mountingInterface: EOAT_PRESETS[0].mountingInterface,
  nozzles: EOAT_PRESETS[0].nozzles
};

export const DIE_PRESETS: DieModel[] = [
  {
    id: 'die-transmission-case',
    name: 'V6 Auto-Transmission Housing (Die Set)',
    category: 'automotive',
    material: 'Premium H13 Tool Steel (1.2344 ESR)',
    operatingTempCelsius: 285,
    dimensions: {
      width: 780,
      height: 680,
      depth: 210
    },
    fixedDieOffsetZ: -450,
    movableDieOffsetZ: 450,
    dieOpeningDistance: 900,
    features: [
      { id: 'f1', name: 'Main Gear Chamber Pocket', type: 'pocket', position: [-80, 20, -50], dimensions: [260, 240, 110], targetThicknessMicrons: 30, criticality: 'high' },
      { id: 'f2', name: 'Torque Converter Bell Core', type: 'pocket', position: [120, -40, -40], dimensions: [210, 210, 95], targetThicknessMicrons: 35, criticality: 'high' },
      { id: 'f3', name: 'Hydraulic Valve Body Ribs', type: 'rib', position: [-130, -120, -20], dimensions: [140, 80, 40], targetThicknessMicrons: 25, criticality: 'medium' },
      { id: 'f4', name: 'Oil Cooler Boss & Ejector Pin', type: 'core_pin', position: [90, 140, -10], dimensions: [45, 45, 70], targetThicknessMicrons: 40, criticality: 'high' },
      { id: 'f5', name: 'Inlet Runner Gate', type: 'gate', position: [0, -260, -30], dimensions: [120, 35, 25], targetThicknessMicrons: 35, criticality: 'high' }
    ]
  },
  {
    id: 'die-ev-battery-tray',
    name: 'EV Lower Battery Enclosure Tray (Structural)',
    category: 'energy',
    material: 'Dievar / H11 Heat-Treated Alloy',
    operatingTempCelsius: 270,
    dimensions: {
      width: 1100,
      height: 820,
      depth: 140
    },
    fixedDieOffsetZ: -550,
    movableDieOffsetZ: 550,
    dieOpeningDistance: 1100,
    features: [
      { id: 'ev1', name: 'Cell Bay 1 Cooling Floor', type: 'pocket', position: [-280, 0, -30], dimensions: [260, 380, 45], targetThicknessMicrons: 22, criticality: 'high' },
      { id: 'ev2', name: 'Cell Bay 2 Cooling Floor', type: 'pocket', position: [0, 0, -30], dimensions: [260, 380, 45], targetThicknessMicrons: 22, criticality: 'high' },
      { id: 'ev3', name: 'Cell Bay 3 Cooling Floor', type: 'pocket', position: [280, 0, -30], dimensions: [260, 380, 45], targetThicknessMicrons: 22, criticality: 'high' },
      { id: 'ev4', name: 'Perimeter Crash Ribbing', type: 'rib', position: [0, 320, -15], dimensions: [920, 60, 35], targetThicknessMicrons: 28, criticality: 'medium' }
    ]
  },
  {
    id: 'die-shock-tower',
    name: 'Front Shock Tower (Mega Cast)',
    category: 'automotive',
    material: '1.2367 High Toughness Tool Steel',
    operatingTempCelsius: 310,
    dimensions: {
      width: 640,
      height: 720,
      depth: 260
    },
    fixedDieOffsetZ: -480,
    movableDieOffsetZ: 480,
    dieOpeningDistance: 960,
    features: [
      { id: 'st1', name: 'Spring Dome Deep Cavity', type: 'pocket', position: [0, 60, -70], dimensions: [240, 240, 160], targetThicknessMicrons: 38, criticality: 'high' },
      { id: 'st2', name: 'Chassis Mount Flanges', type: 'rib', position: [-140, -150, -25], dimensions: [120, 160, 50], targetThicknessMicrons: 26, criticality: 'medium' },
      { id: 'st3', name: 'Central Deep Core Pin', type: 'core_pin', position: [0, 60, 20], dimensions: [55, 55, 110], targetThicknessMicrons: 45, criticality: 'high' }
    ]
  },
  {
    id: 'die-heat-sink',
    name: '5G Base Station Pin-Fin Heat Sink',
    category: 'electronics',
    material: 'Standard H13 Tool Steel',
    operatingTempCelsius: 240,
    dimensions: {
      width: 520,
      height: 480,
      depth: 90
    },
    fixedDieOffsetZ: -380,
    movableDieOffsetZ: 380,
    dieOpeningDistance: 760,
    features: [
      { id: 'hs1', name: 'Dense Fin Matrix Cavity', type: 'rib', position: [0, 0, -25], dimensions: [360, 340, 60], targetThicknessMicrons: 32, criticality: 'high' },
      { id: 'hs2', name: 'Thermal Base Plate Boss', type: 'pocket', position: [0, -120, -10], dimensions: [180, 100, 30], targetThicknessMicrons: 20, criticality: 'normal' }
    ]
  }
];

export const DEFAULT_WAYPOINTS: Waypoint[] = [
  {
    id: 'wp-home',
    index: 0,
    name: '1. HOME / PURGE (Safe Standby)',
    x: 0,
    y: 240,
    z: -195,
    rx: 90,
    ry: 0,
    rz: 90,
    jointAnglesDeg: [90.0, 130.0, -145.0, 0.0, 15.0, 0.0],
    motionType: 'JOINT',
    speed: 1200,
    acceleration: 2500,
    blendRadius: 0,
    dwellTimeSec: 0.5,
    action: 'MICRO_PURGE',
    targetFace: 'TRANSIT',
    lubePressureBar: 3.5,
    airPressureBar: 4.5,
    flowRateMlPerSec: 10,
    nozzleFanAngleDeg: 60,
    standoffDistanceMm: 500
  },
  {
    id: 'wp-wait-open',
    index: 1,
    name: '2. WAIT FOR DIE OPEN (Boundary)',
    x: 0,
    y: 165,
    z: -79,
    rx: 90,
    ry: 0,
    rz: 90,
    jointAnglesDeg: [90.0, 125.0, -135.0, 0.0, 10.0, 0.0],
    motionType: 'JOINT',
    speed: 900,
    acceleration: 2200,
    blendRadius: 30,
    dwellTimeSec: 0.2,
    action: 'NONE',
    targetFace: 'TRANSIT',
    lubePressureBar: 0,
    airPressureBar: 0,
    flowRateMlPerSec: 0,
    nozzleFanAngleDeg: 60,
    standoffDistanceMm: 400
  },
  {
    id: 'wp-approach',
    index: 2,
    name: '3. APPROACH (Toward Open Daylight)',
    x: 0,
    y: 96,
    z: -10,
    rx: 90,
    ry: 0,
    rz: 90,
    jointAnglesDeg: [90.0, 120.0, -128.0, 0.0, 8.0, 0.0],
    motionType: 'JOINT',
    speed: 850,
    acceleration: 2200,
    blendRadius: 35,
    dwellTimeSec: 0,
    action: 'NONE',
    targetFace: 'TRANSIT',
    lubePressureBar: 0,
    airPressureBar: 0,
    flowRateMlPerSec: 0,
    nozzleFanAngleDeg: 60,
    standoffDistanceMm: 300
  },
  {
    id: 'wp-enter-die',
    index: 3,
    name: '4. ENTER DIE (Safety Clearance Zone)',
    x: 0,
    y: 50,
    z: 0,
    rx: 90,
    ry: 0,
    rz: 90,
    jointAnglesDeg: [90.0, 116.3, -125.5, 0.0, 9.1, 0.0],
    motionType: 'LINEAR',
    speed: 650,
    acceleration: 1800,
    blendRadius: 25,
    dwellTimeSec: 0,
    action: 'NONE',
    targetFace: 'TRANSIT',
    lubePressureBar: 0,
    airPressureBar: 0,
    flowRateMlPerSec: 0,
    nozzleFanAngleDeg: 60,
    standoffDistanceMm: 220
  },
  {
    id: 'wp-ready-spray',
    index: 4,
    name: '5. READY TO SPRAY (Center Aligned)',
    x: 0,
    y: 20,
    z: -310,
    rx: 90,
    ry: 0,
    rz: 90,
    jointAnglesDeg: [90.0, 102.5, -140.7, 0.0, 38.2, 0.0],
    motionType: 'LINEAR',
    speed: 500,
    acceleration: 1500,
    blendRadius: 20,
    dwellTimeSec: 0.1,
    action: 'NONE',
    targetFace: 'FIXED_DIE',
    lubePressureBar: 0,
    airPressureBar: 0,
    flowRateMlPerSec: 0,
    nozzleFanAngleDeg: 70,
    standoffDistanceMm: 140
  },
  {
    id: 'wp-fixed-top',
    index: 5,
    name: '6a. SPRAY FIXED DIE (Top Pass)',
    x: -100,
    y: 70,
    z: -310,
    rx: 90,
    ry: 0,
    rz: 90,
    jointAnglesDeg: [106.6, 107.8, -142.9, 0.0, 35.2, -16.6],
    motionType: 'LINEAR',
    speed: 350,
    acceleration: 1800,
    blendRadius: 30,
    dwellTimeSec: 0.15,
    action: 'LUBE_SPRAY',
    targetFace: 'FIXED_DIE',
    lubePressureBar: 4.2,
    airPressureBar: 5.5,
    flowRateMlPerSec: 45,
    nozzleFanAngleDeg: 75,
    standoffDistanceMm: 140
  },
  {
    id: 'wp-fixed-bot',
    index: 6,
    name: '6b. SPRAY FIXED DIE (Bottom Pass)',
    x: 100,
    y: -70,
    z: -310,
    rx: 90,
    ry: 0,
    rz: 90,
    jointAnglesDeg: [73.4, 96.5, -134.7, 0.0, 38.3, 16.6],
    motionType: 'LINEAR',
    speed: 350,
    acceleration: 1800,
    blendRadius: 30,
    dwellTimeSec: 0.2,
    action: 'LUBE_SPRAY',
    targetFace: 'FIXED_DIE',
    lubePressureBar: 4.2,
    airPressureBar: 5.5,
    flowRateMlPerSec: 45,
    nozzleFanAngleDeg: 75,
    standoffDistanceMm: 140
  },
  {
    id: 'wp-transition',
    index: 7,
    name: '7. TRANSITION (Cross Daylight)',
    x: 0,
    y: 0,
    z: 0,
    rx: 90,
    ry: 0,
    rz: 90,
    jointAnglesDeg: [90.0, 112.4, -123.2, 0.0, 10.9, 0.0],
    motionType: 'LINEAR',
    speed: 600,
    acceleration: 2000,
    blendRadius: 30,
    dwellTimeSec: 0,
    action: 'NONE',
    targetFace: 'TRANSIT',
    lubePressureBar: 0,
    airPressureBar: 0,
    flowRateMlPerSec: 0,
    nozzleFanAngleDeg: 60,
    standoffDistanceMm: 250
  },
  {
    id: 'wp-mov-top',
    index: 8,
    name: '8a. SPRAY MOVING DIE (Top Pass)',
    x: -100,
    y: 70,
    z: 310,
    rx: 90,
    ry: 0,
    rz: 90,
    jointAnglesDeg: [96.0, 117.0, -103.7, 0.0, -13.2, -6.0],
    motionType: 'LINEAR',
    speed: 350,
    acceleration: 1800,
    blendRadius: 35,
    dwellTimeSec: 0.25,
    action: 'LUBE_SPRAY',
    targetFace: 'MOVABLE_DIE',
    lubePressureBar: 4.0,
    airPressureBar: 5.5,
    flowRateMlPerSec: 42,
    nozzleFanAngleDeg: 75,
    standoffDistanceMm: 140
  },
  {
    id: 'wp-mov-bot',
    index: 9,
    name: '8b. SPRAY MOVING DIE (Bottom Pass)',
    x: 100,
    y: -70,
    z: 310,
    rx: 90,
    ry: 0,
    rz: 90,
    jointAnglesDeg: [84.0, 107.7, -98.2, 0.0, -9.5, 6.0],
    motionType: 'LINEAR',
    speed: 350,
    acceleration: 1800,
    blendRadius: 35,
    dwellTimeSec: 0.2,
    action: 'LUBE_SPRAY',
    targetFace: 'MOVABLE_DIE',
    lubePressureBar: 4.0,
    airPressureBar: 5.5,
    flowRateMlPerSec: 42,
    nozzleFanAngleDeg: 75,
    standoffDistanceMm: 140
  },
  {
    id: 'wp-air-blow',
    index: 10,
    name: '9. AIR BLOW (Drying & Vent Clear)',
    x: 0,
    y: 0,
    z: 0,
    rx: 90,
    ry: 0,
    rz: 90,
    jointAnglesDeg: [90.0, 112.4, -123.2, 0.0, 10.9, 0.0],
    motionType: 'LINEAR',
    speed: 650,
    acceleration: 2000,
    blendRadius: 30,
    dwellTimeSec: 1.2,
    action: 'AIR_BLOW',
    targetFace: 'BOTH',
    lubePressureBar: 0,
    airPressureBar: 6.5,
    flowRateMlPerSec: 0,
    nozzleFanAngleDeg: 85,
    standoffDistanceMm: 180
  },
  {
    id: 'wp-retract',
    index: 11,
    name: '10. EXIT DIE (Controlled Retract)',
    x: 0,
    y: 96,
    z: -10,
    rx: 90,
    ry: 0,
    rz: 90,
    jointAnglesDeg: [90.0, 120.0, -128.0, 0.0, 8.0, 0.0],
    motionType: 'LINEAR',
    speed: 950,
    acceleration: 2400,
    blendRadius: 40,
    dwellTimeSec: 0,
    action: 'NONE',
    targetFace: 'TRANSIT',
    lubePressureBar: 0,
    airPressureBar: 0,
    flowRateMlPerSec: 0,
    nozzleFanAngleDeg: 60,
    standoffDistanceMm: 350
  },
  {
    id: 'wp-clear-machine',
    index: 12,
    name: '11. CLEAR MACHINE (Safety Boundary)',
    x: 0,
    y: 165,
    z: -79,
    rx: 90,
    ry: 0,
    rz: 90,
    jointAnglesDeg: [90.0, 125.0, -135.0, 0.0, 10.0, 0.0],
    motionType: 'JOINT',
    speed: 1000,
    acceleration: 2400,
    blendRadius: 30,
    dwellTimeSec: 0,
    action: 'NONE',
    targetFace: 'TRANSIT',
    lubePressureBar: 0,
    airPressureBar: 0,
    flowRateMlPerSec: 0,
    nozzleFanAngleDeg: 60,
    standoffDistanceMm: 450
  },
  {
    id: 'wp-return-home',
    index: 13,
    name: '12. HOME STANDBY (Robot Clear)',
    x: 0,
    y: 240,
    z: -195,
    rx: 90,
    ry: 0,
    rz: 90,
    jointAnglesDeg: [90.0, 130.0, -145.0, 0.0, 15.0, 0.0],
    motionType: 'JOINT',
    speed: 1200,
    acceleration: 2500,
    blendRadius: 0,
    dwellTimeSec: 0,
    action: 'NONE',
    targetFace: 'TRANSIT',
    lubePressureBar: 0,
    airPressureBar: 0,
    flowRateMlPerSec: 0,
    nozzleFanAngleDeg: 60,
    standoffDistanceMm: 500
  }
];
