import { DieModel } from '../types/die';
import { RobotModelSpec, ToolCenterPoint, SprayHeadType, SprayNozzleConfig, HotSpotDefinition } from '../types/robot';
import { DieCastingMachine } from '../types/machine';
import { Waypoint } from '../types/path';

export const TOYO_DCM_FAMILY: DieCastingMachine[] = [
  {
    id: 'toyo-bd-125v7ex',
    name: 'Toyo BD-125V7EX (1,250 kN / 125T)',
    modelCode: 'BD-125V7EX',
    manufacturer: 'TOYO',
    clampingForceKn: 1250,
    clampingForceTons: 125,
    tieBarClearanceH: 460,
    tieBarClearanceV: 460,
    tieBarDiameter: 85,
    platenWidth: 700,
    platenHeight: 700,
    movablePlatenWidth: 700,
    movablePlatenHeight: 700,
    maxDieOpeningStroke: 350,
    minDieHeight: 250,
    maxDieHeight: 500,
    ejectorStroke: 75,
    injectionAxisOffsetY: -100,
    safetyEnclosureDepth: 2200,
    plungerLubricatorModel: 'DM05/DC-TY-B1',
    plungerStroke: 305,
    standardPlungerDia: 50,
    machineLengthMm: 4585,
    machineWidthMm: 1575,
    machineHeightMm: 2207,
    machineWeightTons: 5.5,
    dryCycleTimeSec: 6.0,
    controlSystem: 'SYSTEM 700EX',
    pumpMotorPower: '15kW 6P AC200V',
    oilTankCapacityL: 330
  },
  {
    id: 'toyo-bd-200v7ex',
    name: 'Toyo BD-200V7EX (2,000 kN / 200T)',
    modelCode: 'BD-200V7EX',
    manufacturer: 'TOYO',
    clampingForceKn: 2000,
    clampingForceTons: 200,
    tieBarClearanceH: 508,
    tieBarClearanceV: 530,
    tieBarDiameter: 100,
    platenWidth: 820,
    platenHeight: 820,
    movablePlatenWidth: 820,
    movablePlatenHeight: 820,
    maxDieOpeningStroke: 350,
    minDieHeight: 250,
    maxDieHeight: 600,
    ejectorStroke: 80,
    injectionAxisOffsetY: -125,
    safetyEnclosureDepth: 2400,
    plungerLubricatorModel: 'DM05/DC-TY-B1',
    plungerStroke: 370,
    standardPlungerDia: 50,
    machineLengthMm: 5407,
    machineWidthMm: 1796,
    machineHeightMm: 2545,
    machineWeightTons: 8.0,
    dryCycleTimeSec: 7.7,
    controlSystem: 'SYSTEM 700EX',
    pumpMotorPower: '15kW 6P AC200V',
    oilTankCapacityL: 400
  },
  {
    id: 'toyo-bd-250v7ex',
    name: 'Toyo BD-250V7EX (2,500 kN / 250T)',
    modelCode: 'BD-250V7EX',
    manufacturer: 'TOYO',
    clampingForceKn: 2500,
    clampingForceTons: 250,
    tieBarClearanceH: 584,
    tieBarClearanceV: 584,
    tieBarDiameter: 110,
    platenWidth: 850,
    platenHeight: 850,
    movablePlatenWidth: 850,
    movablePlatenHeight: 904,
    maxDieOpeningStroke: 380,
    minDieHeight: 250,
    maxDieHeight: 600,
    ejectorStroke: 80,
    injectionAxisOffsetY: -125,
    safetyEnclosureDepth: 2600,
    plungerLubricatorModel: 'DM05/DC-TY-B1',
    plungerStroke: 370,
    standardPlungerDia: 60,
    machineLengthMm: 5603,
    machineWidthMm: 1947,
    machineHeightMm: 2601,
    machineWeightTons: 9.0,
    dryCycleTimeSec: 7.0,
    controlSystem: 'SYSTEM 700EX',
    pumpMotorPower: '22kW 6P AC200V',
    oilTankCapacityL: 410
  },
  {
    id: 'toyo-bd-350v7ex',
    name: 'Toyo BD-350V7EX (3,500 kN / 350T)',
    modelCode: 'BD-350V7EX',
    manufacturer: 'TOYO',
    clampingForceKn: 3500,
    clampingForceTons: 350,
    tieBarClearanceH: 652,
    tieBarClearanceV: 652,
    tieBarDiameter: 125,
    platenWidth: 935,
    platenHeight: 1008,
    movablePlatenWidth: 935,
    movablePlatenHeight: 1008,
    maxDieOpeningStroke: 420,
    minDieHeight: 300,
    maxDieHeight: 700,
    ejectorStroke: 100,
    injectionAxisOffsetY: -150,
    safetyEnclosureDepth: 2800,
    plungerLubricatorModel: 'DM05/DC-TY-B1',
    plungerStroke: 425,
    standardPlungerDia: 70,
    machineLengthMm: 6185,
    machineWidthMm: 2019,
    machineHeightMm: 2786,
    machineWeightTons: 12.0,
    dryCycleTimeSec: 10.9,
    controlSystem: 'SYSTEM 700EX',
    pumpMotorPower: '22kW 6P AC200V',
    oilTankCapacityL: 500
  },
  {
    id: 'toyo-bd-500v7ex',
    name: 'Toyo BD-500V7EX (5,000 kN / 500T)',
    modelCode: 'BD-500V7EX',
    manufacturer: 'TOYO',
    clampingForceKn: 5000,
    clampingForceTons: 500,
    tieBarClearanceH: 751,
    tieBarClearanceV: 751,
    tieBarDiameter: 140,
    platenWidth: 1175.5,
    platenHeight: 1200,
    movablePlatenWidth: 1070,
    movablePlatenHeight: 1172,
    maxDieOpeningStroke: 560,
    minDieHeight: 350,
    maxDieHeight: 850,
    ejectorStroke: 110,
    injectionAxisOffsetY: -175,
    safetyEnclosureDepth: 3200,
    plungerLubricatorModel: 'DM10/DC-TY-B1',
    plungerStroke: 580,
    standardPlungerDia: 80,
    machineLengthMm: 7386,
    machineWidthMm: 2416,
    machineHeightMm: 2945,
    machineWeightTons: 19.0,
    dryCycleTimeSec: 11.1,
    controlSystem: 'SYSTEM 700EX',
    pumpMotorPower: '37kW 6P AC200V',
    oilTankCapacityL: 890
  },
  {
    id: 'toyo-bd-650v7ex',
    name: 'Toyo BD-650V7EX (6,500 kN / 650T)',
    modelCode: 'BD-650V7EX',
    manufacturer: 'TOYO',
    clampingForceKn: 6500,
    clampingForceTons: 650,
    tieBarClearanceH: 850,
    tieBarClearanceV: 850,
    tieBarDiameter: 160,
    platenWidth: 1320,
    platenHeight: 1335,
    movablePlatenWidth: 1200,
    movablePlatenHeight: 1302,
    maxDieOpeningStroke: 660,
    minDieHeight: 350,
    maxDieHeight: 900,
    ejectorStroke: 125,
    injectionAxisOffsetY: -225,
    safetyEnclosureDepth: 3400,
    plungerLubricatorModel: 'DM10/DC-TY-B1',
    plungerStroke: 670,
    standardPlungerDia: 80,
    machineLengthMm: 7830,
    machineWidthMm: 2495,
    machineHeightMm: 2972,
    machineWeightTons: 25.0,
    dryCycleTimeSec: 13.2,
    controlSystem: 'SYSTEM 700EX',
    pumpMotorPower: '37kW 6P AC200V',
    oilTankCapacityL: 920
  },
  {
    id: 'toyo-bd-800v7ex',
    name: 'Toyo BD-800V7EX (8,000 kN / 800T)',
    modelCode: 'BD-800V7EX',
    manufacturer: 'TOYO',
    clampingForceKn: 8000,
    clampingForceTons: 800,
    tieBarClearanceH: 931,
    tieBarClearanceV: 931,
    tieBarDiameter: 180,
    platenWidth: 1440.5,
    platenHeight: 1475,
    movablePlatenWidth: 1400,
    movablePlatenHeight: 1442,
    maxDieOpeningStroke: 760,
    minDieHeight: 400,
    maxDieHeight: 950,
    ejectorStroke: 125,
    injectionAxisOffsetY: -275,
    safetyEnclosureDepth: 3600,
    plungerLubricatorModel: 'DM10/DC-TY-B1',
    plungerStroke: 750,
    standardPlungerDia: 90,
    machineLengthMm: 8622,
    machineWidthMm: 2753,
    machineHeightMm: 3360,
    machineWeightTons: 32.0,
    dryCycleTimeSec: 15.3,
    controlSystem: 'SYSTEM 700EX',
    pumpMotorPower: '45kW 6P AC200V',
    oilTankCapacityL: 970
  },
  {
    id: 'toyo-bd-1000v7ex',
    name: 'Toyo BD-1000V7EX (10,000 kN / 1000T)',
    modelCode: 'BD-1000V7EX',
    manufacturer: 'TOYO',
    clampingForceKn: 10000,
    clampingForceTons: 1000,
    tieBarClearanceH: 931,
    tieBarClearanceV: 931,
    tieBarDiameter: 190,
    platenWidth: 1440.5,
    platenHeight: 1475,
    movablePlatenWidth: 1400,
    movablePlatenHeight: 1442,
    maxDieOpeningStroke: 760,
    minDieHeight: 400,
    maxDieHeight: 950,
    ejectorStroke: 125,
    injectionAxisOffsetY: -275,
    safetyEnclosureDepth: 3600,
    plungerLubricatorModel: 'DM10/DC-TY-B1',
    plungerStroke: 750,
    standardPlungerDia: 100,
    machineLengthMm: 8622,
    machineWidthMm: 2753,
    machineHeightMm: 3360,
    machineWeightTons: 33.0,
    dryCycleTimeSec: 17.9,
    controlSystem: 'SYSTEM 700EX',
    pumpMotorPower: '45kW 6P AC200V',
    oilTankCapacityL: 970
  },
  {
    id: 'toyo-bd-1250v7ex',
    name: 'Toyo BD-1250V7EX (12,500 kN / 1250T)',
    modelCode: 'BD-1250V7EX',
    manufacturer: 'TOYO',
    clampingForceKn: 12500,
    clampingForceTons: 1250,
    tieBarClearanceH: 1150,
    tieBarClearanceV: 1150,
    tieBarDiameter: 230,
    platenWidth: 1800,
    platenHeight: 1800,
    movablePlatenWidth: 1800,
    movablePlatenHeight: 1800,
    maxDieOpeningStroke: 900,
    minDieHeight: 600,
    maxDieHeight: 1500,
    ejectorStroke: 200,
    injectionAxisOffsetY: -350,
    safetyEnclosureDepth: 4500,
    plungerLubricatorModel: 'L-15',
    plungerStroke: 950,
    standardPlungerDia: 120,
    machineLengthMm: 13003,
    machineWidthMm: 3273,
    machineHeightMm: 4538,
    machineWeightTons: 66.0,
    dryCycleTimeSec: 20.8,
    controlSystem: 'SYSTEM 700EX',
    pumpMotorPower: '45kW+30kW 6P AC200V',
    oilTankCapacityL: 1800
  }
];

export const MACHINE_PRESETS: DieCastingMachine[] = TOYO_DCM_FAMILY;

export const ROBOT_PRESETS: RobotModelSpec[] = [
  {
    id: 'yaskawa-gp50',
    name: 'Yaskawa Motoman GP50 (Die-Casting Heavy / Spray Spec)',
    manufacturer: 'YASKAWA',
    payloadKg: 50,
    reachMm: 2061,
    repeatabilityMm: 0.07,
    degreesOfFreedom: 6,
    baseOffset: [0, 850, -180],
    mountOrientation: 'top',
    jointLimits: [
      { minDeg: -180, maxDeg: 180, maxVelocityDegPerSec: 180 },
      { minDeg: -90, maxDeg: 135, maxVelocityDegPerSec: 180 },
      { minDeg: -175, maxDeg: 250, maxVelocityDegPerSec: 180 },
      { minDeg: -360, maxDeg: 360, maxVelocityDegPerSec: 250 },
      { minDeg: -125, maxDeg: 125, maxVelocityDegPerSec: 250 },
      { minDeg: -360, maxDeg: 360, maxVelocityDegPerSec: 360 }
    ],
    dhParams: []
  },
  {
    id: 'yaskawa-gp25-12',
    name: 'Yaskawa Motoman GP25-12 (Extended Reach Die Spray)',
    manufacturer: 'YASKAWA',
    payloadKg: 25,
    reachMm: 2010,
    repeatabilityMm: 0.05,
    degreesOfFreedom: 6,
    baseOffset: [0, 850, -180],
    mountOrientation: 'top',
    jointLimits: [
      { minDeg: -180, maxDeg: 180, maxVelocityDegPerSec: 210 },
      { minDeg: -105, maxDeg: 150, maxVelocityDegPerSec: 210 },
      { minDeg: -175, maxDeg: 240, maxVelocityDegPerSec: 265 },
      { minDeg: -360, maxDeg: 360, maxVelocityDegPerSec: 420 },
      { minDeg: -150, maxDeg: 150, maxVelocityDegPerSec: 420 },
      { minDeg: -360, maxDeg: 360, maxVelocityDegPerSec: 800 }
    ],
    dhParams: []
  },
  {
    id: 'fanuc-m710ic-50',
    name: 'FANUC M-710iC/50 (Foundry Spec)',
    manufacturer: 'FANUC',
    payloadKg: 50,
    reachMm: 2050,
    repeatabilityMm: 0.03,
    degreesOfFreedom: 6,
    baseOffset: [0, 850, -180],
    mountOrientation: 'top',
    jointLimits: [
      { minDeg: -180, maxDeg: 180, maxVelocityDegPerSec: 175 },
      { minDeg: -90, maxDeg: 135, maxVelocityDegPerSec: 175 },
      { minDeg: -170, maxDeg: 260, maxVelocityDegPerSec: 175 },
      { minDeg: -360, maxDeg: 360, maxVelocityDegPerSec: 250 },
      { minDeg: -125, maxDeg: 125, maxVelocityDegPerSec: 250 },
      { minDeg: -360, maxDeg: 360, maxVelocityDegPerSec: 355 }
    ],
    dhParams: []
  },
  {
    id: 'abb-irb-4600',
    name: 'ABB IRB 4600-40/2.55 (Foundry Plus 2)',
    manufacturer: 'ABB',
    payloadKg: 40,
    reachMm: 2550,
    repeatabilityMm: 0.05,
    degreesOfFreedom: 6,
    baseOffset: [-1050, 120, 0],
    mountOrientation: 'side',
    jointLimits: [
      { minDeg: -180, maxDeg: 180, maxVelocityDegPerSec: 175 },
      { minDeg: -90, maxDeg: 150, maxVelocityDegPerSec: 175 },
      { minDeg: -180, maxDeg: 75, maxVelocityDegPerSec: 175 },
      { minDeg: -300, maxDeg: 300, maxVelocityDegPerSec: 250 },
      { minDeg: -120, maxDeg: 120, maxVelocityDegPerSec: 250 },
      { minDeg: -360, maxDeg: 360, maxVelocityDegPerSec: 360 }
    ],
    dhParams: []
  },
  {
    id: 'kuka-kr60-3',
    name: 'KUKA KR 60-3 Foundry',
    manufacturer: 'KUKA',
    payloadKg: 60,
    reachMm: 2033,
    repeatabilityMm: 0.06,
    degreesOfFreedom: 6,
    baseOffset: [-1000, 150, 0],
    mountOrientation: 'side',
    jointLimits: [
      { minDeg: -185, maxDeg: 185, maxVelocityDegPerSec: 156 },
      { minDeg: -135, maxDeg: 35, maxVelocityDegPerSec: 156 },
      { minDeg: -120, maxDeg: 158, maxVelocityDegPerSec: 156 },
      { minDeg: -350, maxDeg: 350, maxVelocityDegPerSec: 330 },
      { minDeg: -119, maxDeg: 119, maxVelocityDegPerSec: 330 },
      { minDeg: -350, maxDeg: 350, maxVelocityDegPerSec: 615 }
    ],
    dhParams: []
  },
  {
    id: 'linear-reciprocator',
    name: 'Wollin / Rimrock 2-Axis Linear Reciprocator',
    manufacturer: 'LINEAR_RECIPROCATOR',
    payloadKg: 45,
    reachMm: 1800,
    repeatabilityMm: 0.2,
    degreesOfFreedom: 2,
    baseOffset: [-900, 0, 300],
    mountOrientation: 'top_machine_mount',
    jointLimits: [
      { minDeg: -1800, maxDeg: 1800, maxVelocityDegPerSec: 500 },
      { minDeg: -1200, maxDeg: 1200, maxVelocityDegPerSec: 500 },
      { minDeg: 0, maxDeg: 0, maxVelocityDegPerSec: 0 },
      { minDeg: 0, maxDeg: 0, maxVelocityDegPerSec: 0 },
      { minDeg: 0, maxDeg: 0, maxVelocityDegPerSec: 0 },
      { minDeg: 0, maxDeg: 0, maxVelocityDegPerSec: 0 }
    ],
    dhParams: []
  }
];

export interface SprayHeadPreset {
  id: SprayHeadType;
  name: string;
  category: string;
  description: string;
  manifoldType: 'single_nozzle' | 'dual_sided_matrix' | 'multi_head_linear' | 'micro_spray';
  manifoldWidthMm: number;
  nozzleCount: number;
  weightKg: number;
  defaultSprayDistanceMm: number;
  nozzles: SprayNozzleConfig[];
  microSpraySettings?: {
    fineSpray: boolean;
    sprayWidthMm: number;
    applicationRateMlPerSec: number;
  };
  conventionalSettings?: {
    liquidFlowMlPerSec: number;
    airPressureBar: number;
    sprayWidthMm: number;
  };
}

export const SPRAY_HEAD_PRESETS: SprayHeadPreset[] = [
  {
    id: 'dual_sided',
    name: 'Dual-Sided / Multi-Directional Head',
    category: 'Double-Acting Matrix',
    description: 'Compact spray head with opposed nozzles facing Fixed and Moving die faces simultaneously. Eliminates excessive wrist twisting in daylight.',
    manifoldType: 'dual_sided_matrix',
    manifoldWidthMm: 280,
    nozzleCount: 8,
    weightKg: 14.5,
    defaultSprayDistanceMm: 140,
    nozzles: [
      { id: 'nz-f1', name: 'Fixed Side Top Left', offsetMm: [-100, 40, 20], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 },
      { id: 'nz-f2', name: 'Fixed Side Top Right', offsetMm: [100, 40, 20], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 },
      { id: 'nz-f3', name: 'Fixed Side Bottom Left', offsetMm: [-100, -40, 20], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 },
      { id: 'nz-f4', name: 'Fixed Side Bottom Right', offsetMm: [100, -40, 20], directionVector: [0, 0, -1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 },
      { id: 'nz-m1', name: 'Moving Side Top Left', offsetMm: [-100, 40, -20], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 },
      { id: 'nz-m2', name: 'Moving Side Top Right', offsetMm: [100, 40, -20], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 },
      { id: 'nz-m3', name: 'Moving Side Bottom Left', offsetMm: [-100, -40, -20], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 },
      { id: 'nz-m4', name: 'Moving Side Bottom Right', offsetMm: [100, -40, -20], directionVector: [0, 0, 1], sprayAngleDeg: 65, type: 'combined', flowRatio: 1.0, sprayWidthMm: 180 }
    ]
  },
  {
    id: 'contour_frame',
    name: 'Contour / Picture-Frame Head',
    category: 'Perimeter Manifold',
    description: 'Conformal rectangular perimeter manifold following die parting line geometry. Delivers uniform enveloping coverage with minimal robot motion.',
    manifoldType: 'multi_head_linear',
    manifoldWidthMm: 420,
    nozzleCount: 12,
    weightKg: 21.0,
    defaultSprayDistanceMm: 160,
    nozzles: [
      { id: 'nz-c1', name: 'Top Left Rim', offsetMm: [-180, 120, 0], directionVector: [0.2, -0.2, -1], sprayAngleDeg: 70, type: 'combined', flowRatio: 1.1, sprayWidthMm: 220 },
      { id: 'nz-c2', name: 'Top Center Rim', offsetMm: [0, 120, 0], directionVector: [0, -0.2, -1], sprayAngleDeg: 70, type: 'combined', flowRatio: 1.0, sprayWidthMm: 220 },
      { id: 'nz-c3', name: 'Top Right Rim', offsetMm: [180, 120, 0], directionVector: [-0.2, -0.2, -1], sprayAngleDeg: 70, type: 'combined', flowRatio: 1.1, sprayWidthMm: 220 },
      { id: 'nz-c4', name: 'Bottom Left Rim', offsetMm: [-180, -120, 0], directionVector: [0.2, 0.2, -1], sprayAngleDeg: 70, type: 'combined', flowRatio: 1.1, sprayWidthMm: 220 },
      { id: 'nz-c5', name: 'Bottom Center Rim', offsetMm: [0, -120, 0], directionVector: [0, 0.2, -1], sprayAngleDeg: 70, type: 'combined', flowRatio: 1.0, sprayWidthMm: 220 },
      { id: 'nz-c6', name: 'Bottom Right Rim', offsetMm: [180, -120, 0], directionVector: [-0.2, 0.2, -1], sprayAngleDeg: 70, type: 'combined', flowRatio: 1.1, sprayWidthMm: 220 }
    ]
  },
  {
    id: 'modular_extension',
    name: 'Modular Extension Head (Deep Cavity)',
    category: 'Articulated Wands',
    description: 'Equipped with extended articulating copper/titanium lance tubes for reaching deep core cavities, slides, and tight tie-bar daylight.',
    manifoldType: 'multi_head_linear',
    manifoldWidthMm: 240,
    nozzleCount: 6,
    weightKg: 12.0,
    defaultSprayDistanceMm: 120,
    nozzles: [
      { id: 'nz-e1', name: 'Deep Well Lance 1', offsetMm: [-60, 0, 120], directionVector: [0, 0, -1], sprayAngleDeg: 55, type: 'lube', flowRatio: 1.3, sprayWidthMm: 140 },
      { id: 'nz-e2', name: 'Deep Well Lance 2', offsetMm: [60, 0, 120], directionVector: [0, 0, -1], sprayAngleDeg: 55, type: 'lube', flowRatio: 1.3, sprayWidthMm: 140 },
      { id: 'nz-e3', name: 'Core Pin Blast', offsetMm: [0, 50, 80], directionVector: [0, -0.3, -1], sprayAngleDeg: 50, type: 'air', flowRatio: 1.0, sprayWidthMm: 120 },
      { id: 'nz-e4', name: 'Slide Face Nozzle', offsetMm: [0, -50, 80], directionVector: [0, 0.3, -1], sprayAngleDeg: 50, type: 'air', flowRatio: 1.0, sprayWidthMm: 120 }
    ]
  },
  {
    id: 'micro_spray',
    name: 'Micro-Spray / MQL Precision Head',
    category: 'Minimum Quantity Lubrication',
    description: 'High-frequency pulsing micro-dosing valves. Generates fine aerosol mist (15-35 µm) with 90% water reduction and near-zero effluent.',
    manifoldType: 'micro_spray',
    manifoldWidthMm: 200,
    nozzleCount: 6,
    weightKg: 8.5,
    defaultSprayDistanceMm: 110,
    microSpraySettings: {
      fineSpray: true,
      sprayWidthMm: 110,
      applicationRateMlPerSec: 18
    },
    nozzles: [
      { id: 'nz-mql1', name: 'Micro Injector L1', offsetMm: [-60, 20, 0], directionVector: [0, 0, -1], sprayAngleDeg: 45, type: 'lube', flowRatio: 0.8, sprayWidthMm: 110 },
      { id: 'nz-mql2', name: 'Micro Injector C1', offsetMm: [0, 20, 0], directionVector: [0, 0, -1], sprayAngleDeg: 45, type: 'lube', flowRatio: 0.8, sprayWidthMm: 110 },
      { id: 'nz-mql3', name: 'Micro Injector R1', offsetMm: [60, 20, 0], directionVector: [0, 0, -1], sprayAngleDeg: 45, type: 'lube', flowRatio: 0.8, sprayWidthMm: 110 },
      { id: 'nz-mql4', name: 'Micro Injector L2', offsetMm: [-60, -20, 0], directionVector: [0, 0, 1], sprayAngleDeg: 45, type: 'lube', flowRatio: 0.8, sprayWidthMm: 110 },
      { id: 'nz-mql5', name: 'Micro Injector C2', offsetMm: [0, -20, 0], directionVector: [0, 0, 1], sprayAngleDeg: 45, type: 'lube', flowRatio: 0.8, sprayWidthMm: 110 },
      { id: 'nz-mql6', name: 'Micro Injector R2', offsetMm: [60, -20, 0], directionVector: [0, 0, 1], sprayAngleDeg: 45, type: 'lube', flowRatio: 0.8, sprayWidthMm: 110 }
    ]
  },
  {
    id: 'conventional_water',
    name: 'Conventional Water-Based Spray Head',
    category: 'High-Volume Emulsion',
    description: 'Robust external-mix twin-fluid block. Provides intensive cooling for high-thermal alloys, thick biscuits, and heavy runner junctions.',
    manifoldType: 'dual_sided_matrix',
    manifoldWidthMm: 320,
    nozzleCount: 10,
    weightKg: 16.5,
    defaultSprayDistanceMm: 160,
    conventionalSettings: {
      liquidFlowMlPerSec: 65,
      airPressureBar: 5.5,
      sprayWidthMm: 220
    },
    nozzles: [
      { id: 'nz-w1', name: 'Cooling Wash Front 1', offsetMm: [-80, 40, 10], directionVector: [0, 0, -1], sprayAngleDeg: 75, type: 'combined', flowRatio: 1.2, sprayWidthMm: 220 },
      { id: 'nz-w2', name: 'Cooling Wash Front 2', offsetMm: [80, 40, 10], directionVector: [0, 0, -1], sprayAngleDeg: 75, type: 'combined', flowRatio: 1.2, sprayWidthMm: 220 },
      { id: 'nz-w3', name: 'Air Blow Jet Front 1', offsetMm: [-80, -40, 10], directionVector: [0, 0, -1], sprayAngleDeg: 80, type: 'air', flowRatio: 1.0, sprayWidthMm: 240 },
      { id: 'nz-w4', name: 'Air Blow Jet Front 2', offsetMm: [80, -40, 10], directionVector: [0, 0, -1], sprayAngleDeg: 80, type: 'air', flowRatio: 1.0, sprayWidthMm: 240 },
      { id: 'nz-w5', name: 'Cooling Wash Rear 1', offsetMm: [-80, 40, -10], directionVector: [0, 0, 1], sprayAngleDeg: 75, type: 'combined', flowRatio: 1.2, sprayWidthMm: 220 },
      { id: 'nz-w6', name: 'Cooling Wash Rear 2', offsetMm: [80, 40, -10], directionVector: [0, 0, 1], sprayAngleDeg: 75, type: 'combined', flowRatio: 1.2, sprayWidthMm: 220 },
      { id: 'nz-w7', name: 'Air Blow Jet Rear 1', offsetMm: [-80, -40, -10], directionVector: [0, 0, 1], sprayAngleDeg: 80, type: 'air', flowRatio: 1.0, sprayWidthMm: 240 },
      { id: 'nz-w8', name: 'Air Blow Jet Rear 2', offsetMm: [80, -40, -10], directionVector: [0, 0, 1], sprayAngleDeg: 80, type: 'air', flowRatio: 1.0, sprayWidthMm: 240 }
    ]
  },
  {
    id: 'hybrid_head',
    name: 'Hybrid Micro + Cooling Blast Head',
    category: 'Dual Circuit System',
    description: 'Dual-circuit system combining micro-spray release film deposition with targeted high-flow cooling blowers for hot spots.',
    manifoldType: 'dual_sided_matrix',
    manifoldWidthMm: 300,
    nozzleCount: 8,
    weightKg: 15.0,
    defaultSprayDistanceMm: 135,
    nozzles: [
      { id: 'nz-hy1', name: 'Cavity Micro Nozzle 1', offsetMm: [-70, 25, 0], directionVector: [0, 0, -1], sprayAngleDeg: 55, type: 'lube', flowRatio: 0.9, sprayWidthMm: 150 },
      { id: 'nz-hy2', name: 'Cavity Micro Nozzle 2', offsetMm: [70, 25, 0], directionVector: [0, 0, -1], sprayAngleDeg: 55, type: 'lube', flowRatio: 0.9, sprayWidthMm: 150 },
      { id: 'nz-hy3', name: 'Biscuit High-Flow Chiller', offsetMm: [0, -40, 0], directionVector: [0, 0, -1], sprayAngleDeg: 85, type: 'combined', flowRatio: 1.6, sprayWidthMm: 250 },
      { id: 'nz-hy4', name: 'Core Drying Air Knife', offsetMm: [0, 50, 0], directionVector: [0, 0, 1], sprayAngleDeg: 90, type: 'air', flowRatio: 1.2, sprayWidthMm: 280 }
    ]
  }
];

export const DEFAULT_HOTSPOTS: HotSpotDefinition[] = [
  {
    id: 'hs-biscuit',
    name: 'Biscuit & Injection Sleeve Hub',
    type: 'biscuit',
    location: [0, -220, -120],
    thermalPriority: 'VERY HOT',
    extraCoolingRequired: true,
    extraPasses: 2,
    slowerSpeedFactor: 0.6,
    surfaceAreaMm2: 9500
  },
  {
    id: 'hs-runner',
    name: 'Main Gate & Ingate Runner',
    type: 'main_gate',
    location: [0, -150, -40],
    thermalPriority: 'HOT',
    extraCoolingRequired: true,
    extraPasses: 1,
    slowerSpeedFactor: 0.75,
    surfaceAreaMm2: 6800
  },
  {
    id: 'hs-corepin',
    name: 'Slender Core Pin Tip',
    type: 'core_pin',
    location: [90, 140, 60],
    thermalPriority: 'VERY HOT',
    extraCoolingRequired: true,
    extraPasses: 2,
    slowerSpeedFactor: 0.5,
    surfaceAreaMm2: 3200
  },
  {
    id: 'hs-thickboss',
    name: 'Bearing Boss Heavy Section',
    type: 'thick_section',
    location: [-80, 20, -50],
    thermalPriority: 'HOT',
    extraCoolingRequired: false,
    extraPasses: 1,
    slowerSpeedFactor: 0.8,
    surfaceAreaMm2: 8400
  }
];

export const TOOL_DEFAULT: ToolCenterPoint = {
  x: 0,
  y: 0,
  z: 220,
  rx: 0,
  ry: 0,
  rz: 0,
  manifoldType: 'dual_sided_matrix',
  sprayHeadType: 'dual_sided',
  nozzleCount: 8,
  manifoldWidthMm: 280,
  weightKg: 14.5,
  nozzles: SPRAY_HEAD_PRESETS[0].nozzles
};

export const DIE_PRESETS: DieModel[] = [
  {
    id: 'die-transmission-case',
    name: 'V6 Auto-Transmission Housing (Die Set)',
    category: 'automotive',
    material: 'Premium H13 Tool Steel (1.2344 ESR)',
    operatingTempCelsius: 285,
    dimensions: {
      width: 780,
      height: 680,
      depth: 210
    },
    fixedDieOffsetZ: -450,
    movableDieOffsetZ: 450,
    dieOpeningDistance: 900,
    features: [
      { id: 'f1', name: 'Main Gear Chamber Pocket', type: 'pocket', position: [-80, 20, -50], dimensions: [260, 240, 110], targetThicknessMicrons: 30, criticality: 'high' },
      { id: 'f2', name: 'Torque Converter Bell Core', type: 'pocket', position: [120, -40, -40], dimensions: [210, 210, 95], targetThicknessMicrons: 35, criticality: 'high' },
      { id: 'f3', name: 'Hydraulic Valve Body Ribs', type: 'rib', position: [-130, -120, -20], dimensions: [140, 80, 40], targetThicknessMicrons: 25, criticality: 'medium' },
      { id: 'f4', name: 'Oil Cooler Boss & Ejector Pin', type: 'core_pin', position: [90, 140, -10], dimensions: [45, 45, 70], targetThicknessMicrons: 40, criticality: 'high' },
      { id: 'f5', name: 'Inlet Runner Gate', type: 'gate', position: [0, -260, -30], dimensions: [120, 35, 25], targetThicknessMicrons: 35, criticality: 'high' }
    ]
  },
  {
    id: 'die-ev-battery-tray',
    name: 'EV Lower Battery Enclosure Tray (Structural)',
    category: 'energy',
    material: 'Dievar / H11 Heat-Treated Alloy',
    operatingTempCelsius: 270,
    dimensions: {
      width: 1100,
      height: 820,
      depth: 140
    },
    fixedDieOffsetZ: -550,
    movableDieOffsetZ: 550,
    dieOpeningDistance: 1100,
    features: [
      { id: 'ev1', name: 'Cell Bay 1 Cooling Floor', type: 'pocket', position: [-280, 0, -30], dimensions: [260, 380, 45], targetThicknessMicrons: 22, criticality: 'high' },
      { id: 'ev2', name: 'Cell Bay 2 Cooling Floor', type: 'pocket', position: [0, 0, -30], dimensions: [260, 380, 45], targetThicknessMicrons: 22, criticality: 'high' },
      { id: 'ev3', name: 'Cell Bay 3 Cooling Floor', type: 'pocket', position: [280, 0, -30], dimensions: [260, 380, 45], targetThicknessMicrons: 22, criticality: 'high' },
      { id: 'ev4', name: 'Perimeter Crash Ribbing', type: 'rib', position: [0, 320, -15], dimensions: [920, 60, 35], targetThicknessMicrons: 28, criticality: 'medium' }
    ]
  },
  {
    id: 'die-shock-tower',
    name: 'Front Shock Tower (Mega Cast)',
    category: 'automotive',
    material: '1.2367 High Toughness Tool Steel',
    operatingTempCelsius: 310,
    dimensions: {
      width: 640,
      height: 720,
      depth: 260
    },
    fixedDieOffsetZ: -480,
    movableDieOffsetZ: 480,
    dieOpeningDistance: 960,
    features: [
      { id: 'st1', name: 'Spring Dome Deep Cavity', type: 'pocket', position: [0, 60, -70], dimensions: [240, 240, 160], targetThicknessMicrons: 38, criticality: 'high' },
      { id: 'st2', name: 'Chassis Mount Flanges', type: 'rib', position: [-140, -150, -25], dimensions: [120, 160, 50], targetThicknessMicrons: 26, criticality: 'medium' },
      { id: 'st3', name: 'Central Deep Core Pin', type: 'core_pin', position: [0, 60, 20], dimensions: [55, 55, 110], targetThicknessMicrons: 45, criticality: 'high' }
    ]
  },
  {
    id: 'die-heat-sink',
    name: '5G Base Station Pin-Fin Heat Sink',
    category: 'electronics',
    material: 'Standard H13 Tool Steel',
    operatingTempCelsius: 240,
    dimensions: {
      width: 520,
      height: 480,
      depth: 90
    },
    fixedDieOffsetZ: -380,
    movableDieOffsetZ: 380,
    dieOpeningDistance: 760,
    features: [
      { id: 'hs1', name: 'Dense Fin Matrix Cavity', type: 'rib', position: [0, 0, -25], dimensions: [360, 340, 60], targetThicknessMicrons: 32, criticality: 'high' },
      { id: 'hs2', name: 'Thermal Base Plate Boss', type: 'pocket', position: [0, -120, -10], dimensions: [180, 100, 30], targetThicknessMicrons: 20, criticality: 'normal' }
    ]
  }
];

export const DEFAULT_WAYPOINTS: Waypoint[] = [
  {
    id: 'wp-home',
    index: 0,
    name: 'P01: Home Standby (Safe)',
    x: -800,
    y: 0,
    z: 550,
    rx: 0,
    ry: 0,
    rz: 0,
    motionType: 'JOINT',
    speed: 1200,
    acceleration: 2500,
    blendRadius: 50,
    dwellTimeSec: 0,
    action: 'NONE',
    targetFace: 'TRANSIT',
    lubePressureBar: 0,
    airPressureBar: 0,
    flowRateMlPerSec: 0,
    nozzleFanAngleDeg: 60,
    standoffDistanceMm: 500
  },
  {
    id: 'wp-entry',
    index: 1,
    name: 'P02: Die Entry Approach',
    x: -450,
    y: 0,
    z: 200,
    rx: 15,
    ry: 0,
    rz: -10,
    motionType: 'LINEAR',
    speed: 800,
    acceleration: 2000,
    blendRadius: 30,
    dwellTimeSec: 0,
    action: 'NONE',
    targetFace: 'TRANSIT',
    lubePressureBar: 0,
    airPressureBar: 0,
    flowRateMlPerSec: 0,
    nozzleFanAngleDeg: 60,
    standoffDistanceMm: 350
  },
  {
    id: 'wp-fixed-top',
    index: 2,
    name: 'P03: Fixed Die Top Spray',
    x: -180,
    y: 180,
    z: -80,
    rx: 40,
    ry: -20,
    rz: 45,
    motionType: 'LINEAR',
    speed: 350,
    acceleration: 1500,
    blendRadius: 15,
    dwellTimeSec: 0.3,
    action: 'LUBE_AND_AIR',
    targetFace: 'FIXED_DIE',
    lubePressureBar: 3.2,
    airPressureBar: 4.5,
    flowRateMlPerSec: 42,
    nozzleFanAngleDeg: 65,
    standoffDistanceMm: 140
  },
  {
    id: 'wp-fixed-cavity',
    index: 3,
    name: 'P04: Fixed Deep Cavity Dwell',
    x: -120,
    y: -20,
    z: -140,
    rx: 50,
    ry: 0,
    rz: 90,
    motionType: 'LINEAR',
    speed: 220,
    acceleration: 1000,
    blendRadius: 10,
    dwellTimeSec: 0.8,
    action: 'LUBE_AND_AIR',
    targetFace: 'FIXED_DIE',
    lubePressureBar: 3.8,
    airPressureBar: 5.0,
    flowRateMlPerSec: 55,
    nozzleFanAngleDeg: 70,
    standoffDistanceMm: 120
  },
  {
    id: 'wp-fixed-runner',
    index: 4,
    name: 'P05: Gate & Sprue Lubrication',
    x: -100,
    y: -180,
    z: -80,
    rx: 35,
    ry: 15,
    rz: 80,
    motionType: 'LINEAR',
    speed: 380,
    acceleration: 1600,
    blendRadius: 20,
    dwellTimeSec: 0.4,
    action: 'LUBE_SPRAY',
    targetFace: 'FIXED_DIE',
    lubePressureBar: 3.5,
    airPressureBar: 4.2,
    flowRateMlPerSec: 48,
    nozzleFanAngleDeg: 60,
    standoffDistanceMm: 135
  },
  {
    id: 'wp-pivot-center',
    index: 5,
    name: 'P06: Platen Center Transfer',
    x: 0,
    y: 0,
    z: 0,
    rx: 0,
    ry: 0,
    rz: 0,
    motionType: 'LINEAR',
    speed: 600,
    acceleration: 2200,
    blendRadius: 30,
    dwellTimeSec: 0,
    action: 'NONE',
    targetFace: 'TRANSIT',
    lubePressureBar: 0,
    airPressureBar: 0,
    flowRateMlPerSec: 0,
    nozzleFanAngleDeg: 60,
    standoffDistanceMm: 280
  },
  {
    id: 'wp-movable-ejectors',
    index: 6,
    name: 'P07: Movable Core & Ejector Spray',
    x: 140,
    y: -120,
    z: -60,
    rx: -45,
    ry: 15,
    rz: -80,
    motionType: 'LINEAR',
    speed: 300,
    acceleration: 1400,
    blendRadius: 15,
    dwellTimeSec: 0.6,
    action: 'LUBE_AND_AIR',
    targetFace: 'MOVABLE_DIE',
    lubePressureBar: 3.5,
    airPressureBar: 4.8,
    flowRateMlPerSec: 50,
    nozzleFanAngleDeg: 65,
    standoffDistanceMm: 130
  },
  {
    id: 'wp-movable-core',
    index: 7,
    name: 'P08: Movable Core Pin Cool-Down',
    x: 160,
    y: 100,
    z: -90,
    rx: -55,
    ry: -10,
    rz: -90,
    motionType: 'LINEAR',
    speed: 260,
    acceleration: 1200,
    blendRadius: 15,
    dwellTimeSec: 0.7,
    action: 'LUBE_AND_AIR',
    targetFace: 'MOVABLE_DIE',
    lubePressureBar: 4.0,
    airPressureBar: 5.2,
    flowRateMlPerSec: 58,
    nozzleFanAngleDeg: 70,
    standoffDistanceMm: 115
  },
  {
    id: 'wp-air-blow',
    index: 8,
    name: 'P09: Residual Blow Dry Pass',
    x: 100,
    y: 0,
    z: 40,
    rx: -20,
    ry: 0,
    rz: 0,
    motionType: 'LINEAR',
    speed: 550,
    acceleration: 2000,
    blendRadius: 25,
    dwellTimeSec: 0.5,
    action: 'AIR_BLOW',
    targetFace: 'BOTH',
    lubePressureBar: 0,
    airPressureBar: 5.8,
    flowRateMlPerSec: 0,
    nozzleFanAngleDeg: 80,
    standoffDistanceMm: 190
  },
  {
    id: 'wp-exit',
    index: 9,
    name: 'P10: Die Exit Retract',
    x: -500,
    y: 0,
    z: 300,
    rx: 10,
    ry: 0,
    rz: 0,
    motionType: 'LINEAR',
    speed: 950,
    acceleration: 2500,
    blendRadius: 40,
    dwellTimeSec: 0,
    action: 'NONE',
    targetFace: 'TRANSIT',
    lubePressureBar: 0,
    airPressureBar: 0,
    flowRateMlPerSec: 0,
    nozzleFanAngleDeg: 60,
    standoffDistanceMm: 450
  },
  {
    id: 'wp-return-home',
    index: 10,
    name: 'P11: Home Standby',
    x: -800,
    y: 0,
    z: 550,
    rx: 0,
    ry: 0,
    rz: 0,
    motionType: 'JOINT',
    speed: 1200,
    acceleration: 2500,
    blendRadius: 0,
    dwellTimeSec: 0,
    action: 'NONE',
    targetFace: 'TRANSIT',
    lubePressureBar: 0,
    airPressureBar: 0,
    flowRateMlPerSec: 0,
    nozzleFanAngleDeg: 60,
    standoffDistanceMm: 500
  }
];
